### ISSUE TITLE
ModelSchema shouldn't take into account private _attributes

### ISSUE THREAD

**Issue by alexandre-janniaux** [marshmallow-code/marshmallow-sqlalchemy#102]
Hi, 

I work on a project with marshmallow_sqlalchemy and sqlalchemy_i18n. When I try to build a schema using ModelSchema and Translatable (from i18n), it outputs the different translations field added by sqlalchemy_i18n, even though an underscore prefixes them. After reading the code of both sqlalchemy projects, I understood these fields are taken into account because they are manytomany relations, so they account for a field of sqlalchemy. 

My understanding of PEP8 for naming style (https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) is that having a leading underscore for attributes means they should only be used internally, and I find strange that marshmallow_sqlalchemy has not this behavior.

I understand there might be practical reasons for adding attributes with a leading underscore, but shouldn't it be explicitly added to the schema, or with an option set to true instead ?

**Comment by xarg** [comment]
This is one of the reasons I have on all my ModelSchema's an explicit `fields` prop on the `Meta` class where I define all the fields that I want to be treated. It's annoying, but avoids these kinds of surprises. For example:

```
class UserSchema(ModelSchema):
   ...
    class Meta:
        model = User
        ordered = True
        sqla_session = db.session
        fields = ('id', 'username', ...)
```

I do agree that by default, the `_` and `__` fields should be ignored, not sure why it's not the case. One explanation could be that some people have fields with `_` in their DB.

**Comment by sloria** [comment]
I'm -0 on skipping fields prefixed with `_`. `_id`, for example, is a rather common field name. As @xargs points out, it's a good idea to specify which fields you want to generate explicitly.

In the future, perhaps we could have someway to set a flag on a sqalchemy `Column` that would tell marshmallow-sqlalchemy to skip it. I think it would work with the API proposed in #22.

**Comment by sloria** [comment]
Closing, as I don't have plans to add this in the short term
