### ISSUE TITLE
avoiding circular imports

### ISSUE THREAD

**Issue by aminalaee** [marshmallow-code/marshmallow-sqlalchemy#104]
I have a Flask app that has a structure like the following:

`project`
  -- `users`
    `__init__.py`
    `models.py`
    `views.py`
    `serializers.py`
  -- `genres`
     `__init__.py`
    `models.py`
    `views.py`
    `serializers.py`

I have a ModelSchema class in one of my folders that uses models.py from the other folder. SQLAlchemy by default solves this problem by using the string name of the class but I get circular import errors in Marshmallow SQLAlchemy. Is there a way to solve this? Or shoud I change my structure?

**Comment by xarg** [comment]
If you're using Nested fields you can also use strings. Something like:

```
UserSchema(ma.Schema):
   genres = fields.Nested('GenreSchema', many=True)
```

Just make sure that you import your schemas in your project so that they are visible at the moment of the serialization.

**Comment by aminalaee** [comment]
Thanks. I've found this solves the problem.
