### ISSUE TITLE
proposal: infinitely-recursive model schemas

### ISSUE THREAD

**Issue by dradetsky** [marshmallow-code/marshmallow-sqlalchemy#109]
Right now if I generate a schema for a model which has related objs, those will be represented by `Related` fields, which are just pks. This is obviously the correct default behavior, but for my purposes it would be useful if I could explicitly ask to generate an infinitely-recursive (and thus unserializable) schema, perhaps like

```
class MySchema(ModelSchema):
    class Meta:
        model = MyModel
        infinitely_recursive = True
```

If you look at my [tests for marshmallow-select](https://github.com/marshmallow-code/marshmallow-select/blob/master/tests/test_marshmallow_select.py) (see fixtures `schemas` & `detail_schemas`) hopefully you get the idea. I'd like to generate an infinitely-recursive "Master Schema" for every model I want to serialize, then define several finite subtrees of that schema for each view of the model's data I present in my application.

At the moment, the only way to do this (that I know of) is to define parent schemas with ModelSchema and then manually override each relation field with marshmallow's two-way nesting. Which is fine for the present example (and for fixing the underlying issues), but is going to get boring as I try to scale this up to larger applications.

Note that the aforementioned test is currently broken, and I probably won't have time to fix it until at least this weekend, so the need here is not urgent, but it would be seriously cool if this could be implemented somehow eventually. My knowledge of the marshmallow-sqlalchemy internals is not very deep, but I assume it's at least possible. Is it hard?

I know I'm not the first person to ask something _like_ this, so there's probably lots of other marginally related issues, but I'm not sure whether to link them.

**Comment by dradetsky** [comment]
To clarify, what I want is only something functionally equivalent to the 2-step shallow-schema -> master-schema process that I do in my test. For example, it would not be necessary to recurse on fields where the linked model does not have an explicitly defined schema which is also declared infinitely-recursive (or perhaps "infinitely-recursable"; it need not actually have any relation fields). It would be permitted for marshmallow-sqlalchemy to raise an error if a schema declared infinitely-recursive linked to a model which for which no explicit definition existed.

**Comment by dradetsky** [comment]
Update: fixed marshmallow-select (hopefully), so now this might conceivably be useful.

**Comment by sloria** [comment]
Closing, as this issue has gone stale. Feel free to comment if there's still interest in this
