### ISSUE TITLE
How to auto generate property ?

### ISSUE THREAD

**Issue by eromoe** [marshmallow-code/marshmallow-sqlalchemy#119]
I have a property defined as 
```
   @property
    def doc_count(self):
        return Session.object_session(self).query(Document).with_parent(self, "documents").count()
```
But I found it didn't generate. From doc, I only see :

```
from marshmallow_sqlalchemy import property2field

id_prop = Author.__mapper__.get_property('id')

property2field(id_prop)
```

And example don't contain this too. 
http://marshmallow.readthedocs.io/en/latest/examples.html

Now I have to use `doc_count = fields.Function(lambda obj: obj.doc_count, dump_only=True)` in schema.

I think it is a usual case, should write in docs.

**Comment by timster** [comment]
You can just specify it as a field on the model:

```python

from marshmallow_sqlalchemy import ModelSchema
from marshmallow import fields

class AuthorSchema(ModelSchema):
    doc_count = fields.Int(dump_only=True)
```

**Comment by eromoe** [comment]
@timster  Thanks. But how to make marshmallow_sqlalchemy auto generate property field by default ?

**Comment by sloria** [comment]
@eromoe marshmallow_sqlalchemy won't automatically include properties by default. Otherwise, schemas would have a lot of useless fields on them. For now, you'll need to declare them explicitly.
