### ISSUE TITLE
What the use of inspect.getmro ?

### ISSUE THREAD

**Issue by touilleMan** [marshmallow-code/marshmallow-sqlalchemy#12]
Hi,

I'm currently building a module to integrate marshmallow with mongoengine (see: https://github.com/touilleMan/marshmallow-mongoengine). To do so I started from the codebase of marshmallow-sqlachemy.

Thus, I was wondering what is the use of `inspect.getmro` in the `schema.get_declared_field` function (see https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/marshmallow_sqlalchemy/schema.py#L39) given the loop make use of `opst = klass.opts` (i.e. the real class options) instead of the current motherclass's ones (so something like `opts = base.opts`)

Is it an error or am I missing something ?

**Comment by sloria** [comment]
Good catch; this was an oversight. It is indeed unnecessary. Thanks for reporting.
