### ISSUE TITLE
Specify columns which are dumped

### ISSUE THREAD

**Issue by disconnect3d** [marshmallow-code/marshmallow-sqlalchemy#122]
Is it possible to specify model's fields/columns which will be dumped?

Assuming we have such code:

```python
class SomeModel(model):
    id = Column(Integer, autoincrement=True, primary_key=True)
    name = Column(String, nullable=False, unique=True)


class SomeModelSchema(ModelSchema):
    class Meta:
        model = SomeModel
        fields = (SomeModel.name,)  # <-- wishful thinking;
```

I'd like `SomeModelSchema().dumps(SomeModel_instance)` dump me just `name` column.

Is there any way to achieve sth like this?

**Comment by igortg** [comment]
You could ignore a column on your schema by using the attributes `load_only` and `dump_only`:
```python
class SomeModelSchema(ModelSchema):
    class Meta:
        model = SomeModel

    id = fields.Integer(load_only=True)  # will not dump id field
```

The beauty of *marshmallow-sqlalchemy* is that it tries to guess all columns from your Model class, so you don't need to repeat yourself in the Schema class. If you want to specify each column to be dumped in the Schema, it's better to go with pure [marshmallow](https://github.com/marshmallow-code/marshmallow) to define your Schema.

**Comment by georgreen** [comment]
@disconnect3d 
```python 
SomeModelSchema(exclude=(properties_you_dont_need,)).dumps(SomeModel_instance)
```
Pass a tuple of all properties, that you don't require.

**Comment by disconnect3d** [comment]
@georgreen I don't need it anymore but thanks for the reply. I think that the proposed solutions would satisfy my needs :).

I think the issue can be closed, so I am doing it.
