### ISSUE TITLE
Document how auto generated fields are generated

### ISSUE THREAD

**Issue by italomaia** [marshmallow-code/marshmallow-sqlalchemy#123]
Given a Model, how are ModelSchema fields generated? Does it introspect validation rules? Which? What does it not do?

**Comment by sloria** [comment]
This can definitely be documented better, but for now, you can see how the field generation happens here: https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/be6df3e87c61d699b321e2a1257e5999e46f6ef8/src/marshmallow_sqlalchemy/convert.py#L128-L141
