### ISSUE TITLE
Do make_instance() and custom post_load-methods clash?

### ISSUE THREAD

**Issue by schober-ch** [marshmallow-code/marshmallow-sqlalchemy#125]
Hey,

I'm working on a Flask app using sqlalchemy, marshmallow and marshmallow-sqlalchemy. I implemented a basic API, using pre_load and post-load decorators for some models to change/adjust fields. 

Sometimes I need to create additional sqlA-objects based on the data and for this I use the post_load-decorator. 

(from the docs, as illustration)
```
class AuthorSchema(ModelSchema):
    class Meta:
        model = Author

    @post_load
    def create_stuff(self, data):
        print(type(data))
```

I would expect the `data` variable to be an instance of the SQLA-model, which works for 2 of my models. 

Now, for a third, I get a dictionary. The dictionary already contains the SQLA-instances for nested fields, but is still a dictionary. Digging into the marshmallow-sqlalchemy code and adding some `print`-statements in `ModelSchema.make_instance` showed that this method works correctly (returning the model instance), but I realized that my print-statements in my own `post_load`-method are printed **before** the ones I added to the `make_instance`-method. 
Doing the same for one of the two working schemata the print in my method is printed after the `make_instance`-one.

So, my question: Is it possible that there is some kind of race condition happening between both decorated methods? I found a warning regarding the execution order in the marshmallow-docs (https://marshmallow.readthedocs.io/en/latest/extending.html#pre-post-processor-invocation-order), and both methods are decorated with the `post_load`-decorator - once in my code and once in the ModelSchema-class.

If this seems unreasonable, has anyone any idea why I don't get the expected SQLA-model instance?

And of course, last but not least, thank you for this library!

**Comment by timster** [comment]
The warning in the documetation you linked is exactly what you are experiencing:

> the invocation order of decorated methods of the same type is not guaranteed

In some cases, `make_instance` runs first, and in some cases `create_stuff` runs first and there is no way to control this behavior.

You can get around this by overwriting `make_instance` on your schema, then calling `super().make_instance()` when you want.

```python
@post_load
def make_instance(self, data):
    result = super().make_instance(data)

    # result will be a model instance here

    return result
```

**Comment by schober-ch** [comment]
Thanks for the clarification and the solution! This is better than mine (I called `self.instance = self.make_instance(data)` on my method and worked with `self.instance` for the rest of my code.
