### ISSUE TITLE
Merging values into existing object from database

### ISSUE THREAD

**Issue by tispratik** [marshmallow-code/marshmallow-sqlalchemy#126]
I could not find any documentation around merging incoming json fields with attributes already present in the database object in memory. I came up with the following code to achieve that. Wondering if there is an easier way to do this:

```python
from sqlalchemy.orm.attributes import set_attribute, flag_modified

@post_load
def make_author(self, data):
  author_from_db = db_helper.find_one_by_id(data['author_id'])
  if author_from_db:
    for attr, value in data.iteritems():
      set_attribute(author_from_db, attr, value)
      flag_modified(author_from_db, attr)
    return author_from_db
  else:
    return Author(**data)
```

In the above, `db_helper` is my custom helper to get the object from db like below:
```python
def find_one_by_author_id(author_id):
  authors = find_all_by_author_id([author_id])
  if authors:
    return authors[0]
  return None


def find_all_by_author_id(author_ids):
  session = db_setup.get_session()
  query = session.query(Author).filter(
    Author.author_id.in_(author_ids))
  return query.all()
```

**Comment by timster** [comment]
I believe you just need to pass your instance to the `load` method.

    author = find_one_by_author_id(1234)
    schema.load(json_data, instance=author)

**Comment by tispratik** [comment]
Thanks @timster I tried and got the following error:

`TypeError: load() got an unexpected keyword argument 'instance'`

**Comment by timster** [comment]
Can you post how you define the scheme? Is it a ModelSchema for sure? Or just a regular Schema?

**Comment by tispratik** [comment]
Its a regular `Schema`. I had not known about `ModelSchema`. I will look it up.

`class Author(Schema):`

**Comment by tispratik** [comment]
Thanks @timster that seems to work. A follow up problem i now have is how to selectively format some fields after reading from the database?

**Comment by tispratik** [comment]
Is it possible to specify a method/function for `load_from`?

**Comment by AbdealiLoKo** [comment]
@tispratik could you elaborate on the usecase for the formatting some fields after reading from the database ?
After you read the instance from the DB, cant you just modify the attributes of the instance using normal methods ?

(Closing as the original issue seems resolved)
