### ISSUE TITLE
Single Schema/Model

### ISSUE THREAD

**Issue by bourdeau** [marshmallow-code/marshmallow-sqlalchemy#128]
Hello,

I'm very new to Python and I don't know much about SQLAlchemy and Marshmallow, so I apologize in advance for my ignorance.

I was wondering if it is possible with marshmallow-sqlalchemy to have a single ModelSchema instead of having one Model and one Shema?

In PHP (with Doctrine ORM and JMS serializer) one can define a model attribute as such:

```php
    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=50, nullable=false)
     * @JMS\Expose
     * @JMS\Groups({"mobile", "backoffice", "front"})
     * @JMS\SerializedName("contact_email")
     * @JMS\Since("1.2")
     * @Assert\Email(message="The email '{{ value }}' is not a valid email.", checkMX = true)
     */
    private $email;
```
In PHP we use Annotations a bit like Decorators in Python. This way our model can handle both serilization and db stuff. So you can do stuff like (pseudo code): User.load(json).save()
This way you can have a single model that handle json, xml -> Model -> MySQL, MongoDB, etc.

Is it possible to do such thing with marshmallow-sqlalchemy to avoid having UserBase and UserModeSchema? Inheritance maybe?

Thanks a lot and sorry if my question is silly due to my lack of Python knowledge.

**Comment by AbdealiLoKo** [comment]
I'm pretty late to reply .. but
The recipe at https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#automatically-generating-schemas-for-sqlalchemy-models comes closes to what you want.

There it says you make a model `User`. Use this recipe to automagically make a `User.__marshmallow__` attribute to all your models which give you the schema.
So, `User.__marshmallow__().load(json).save()` would work.

If you want to  modify the attributes of your schema (but not your model) - e.g. make something required=True in the schema but not the model, use the method described in the last section of  https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#overriding-generated-fields and do `info` -> `marshmallow` and add the kwargs there.
```python
class Book(Model):
    # ...

    abstract = Column(
        Text(),
        info=dict(
            marshmallow=dict(required=True),
        ),
    )
```
