### ISSUE TITLE
Question: best way on how to organize CRUD schema objects with marshmallow-sqlalchemy

### ISSUE THREAD

**Issue by nikoladsp** [marshmallow-code/marshmallow-sqlalchemy#154]
Hi,
one question on what is the best practice to organize marshmallow schema objects for CRUD methods. Say, I have a simple class in SqlAlchemy:
```python
class Order(Base):
    __tablename__ = 'Orders'
    
    id = Column(Integer, primary_key=True)
    name = Column(String)
    quantity = Column(Integer)
    placed_at = Column(DateTime)
```
Now, when creating new Order, I need schema that has **name** field only (and eventually **placed_at** automatically set to ```datetime.utcnow()```). When updating, my endpoint for example should allow to change only **name** and **quantity** fields. On reading (and delete) however I want all fields: **id**, **name**, **quantity** and **placed_at** to be serialized (dumped).

What is the best/recommended way to do this: shall I crate one _base_ class, containing the smallest set of attributes and then extend it (subclass it) and add additional fields? Or, shall I simply create different classes with no common class. I prefer using the base class approach whenever possible, but I am not sure will this complicate managing of _dump_only_ and _exclude_fields_ in sub-classes and make code hard to maintain?

Thank you in advance

**Comment by sloria** [comment]
Sorry for the long delay. You need to set `dump_only` for any read-only fields. So if I'm understanding your case correctly, your schema will looks something like

```python
from marshmallow_sqlalchemy import SQLAlchemySchema, auto_field


class OrderSchema(SQLAlchemySchema):
    class Meta:
        model = Order

    id = auto_field(dump_only=True)
    name = auto_field()
    quantity = auto_field()
    placed_at = auto_field(dump_only=True)
```

**Comment by nikoladsp** [comment]
Thanks!

Btw, how much of a speed-up gain in Marshmallow 3 is compared to Marshmallow 2?
