### ISSUE TITLE
AttributeError: type object '<Schema>' has no attribute 'TYPE_MAPPING

### ISSUE THREAD

**Issue by lordlabakdas** [marshmallow-code/marshmallow-sqlalchemy#156]
I am using `marshmallow-sqlalchemy==0.15.0` when i am running into the below problem:

`AttributeError: type object '<Schema>' has no attribute 'TYPE_MAPPING'`

The marshmallow deserialization class I have is given below:

```
from marshmallow_sqlalchemy import ModelSchema
from data_models.entity.user import User
class UserSchema(ModelSchema):
    class Meta:
        model = User
user_schema = UserSchema()
```

My user.py model is given below:

```
from sqlalchemy import Column, Integer, String, ForeignKey
from data_models.db import Base
class User(Base):
    __tablename__ = "user"
    name = Column(String)
    email = Column(String)

    def get_name(self):
        return self.name
```

Is there something I am missing in the above code?

**Comment by sloria** [comment]
You will need to update to marshmallow>=3.0.0b19, which restores `TYPE_MAPPING`: https://marshmallow.readthedocs.io/en/3.0/changelog.html#b19-2018-10-24
