### ISSUE TITLE
Meta.extra_kwargs to allow adding additional kwargs to fields

### ISSUE THREAD

**Issue by cancan101** [marshmallow-code/marshmallow-sqlalchemy#158]
repost from: https://github.com/marshmallow-code/marshmallow-sqlalchemy/pull/133#issuecomment-439099123

Add what DRF does and allow loading extra kwargs for the schema from the schema's meta: https://www.django-rest-framework.org/api-guide/serializers/#additional-keyword-arguments

/CC @jeanphix

**Comment by AbdealiLoKo** [comment]
Taking thhe example from the link ...
```python
class CreateUserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('email', 'username', 'password')
        extra_kwargs = {'password': {'write_only': True}}
```

Is there any benefit of this over: 
```python
class CreateUserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('email', 'username', 'password')
    password = field_for(User, 'password', write_only=True)
```
Other than a bit less to type ?

**Comment by cancan101** [comment]
>Other than a bit less to type

yes, but you can make `extra_kwargs` a property and then dynamically create the kwargs programmatically:

```python
    class Meta:
        model = User
        fields = ('email', 'username', 'password')
        non_negative_fields = (....) # might be a long list

        @property
        def extra_kwargs(self):
            return {k: {'validate': non_negative} for k in self.non_negative_fields}
```
can do the same with eg write_only fields. ie you open up logic to the user.

**Comment by sloria** [comment]
FWIW, we're considering making field generation overrides more concise with https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/240 . It doesn't allow for the dynamic-ness you're describing above, but it's more explicit without being painfully verbose. Thoughts?

**Comment by sloria** [comment]
Closing this for now, since the new `auto_field` should meet the original use case. Feel free to continue discussion if that's not the case
