### ISSUE TITLE
SQLAlchemy Sessions Not Passed to Nested Fields

### ISSUE THREAD

**Issue by ducharmemp** [marshmallow-code/marshmallow-sqlalchemy#159]
https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#smart-nested-field

Using this recipe as a base, I was writing a function to assist with serialization/de-serialization that looks somewhat like the below snippet:

```python
class MySchema(ModelSchema):
    children = SmartNested(ChildModel)
    class Meta:
        model = Model

... 

schema_obj = MySchema(session=session)
schema_obj.dump(data)
```

For the above snippet, data is an object with a children list that is eagerly loaded. Additionally, I don't have a global/thread local SQLAlchemy session object available as I'm using raw SQLAlchemy rather than flask-sqlalchemy because I'm a masochist who likes to reinvent the wheel. The above code (rightfully) throws an exception of "ValueError: Deserialization requires a session", as the SmartNested field's schema doesn't appear to have access to the parent schema object. I went digging through the code and I'm sure this is a non-trivial issue to address, but I admittedly have only been looking at this code base for a day.

Is there a workaround for this or do I have to just bite the bullet and set up a thread local scoped session?

**Comment by ducharmemp** [comment]
I did find a workaround in the marshmallow parent code (although I'm failing to find the link again as my computer forced an update), solution below:

```python
class CustomSchema(ModelSchema):
    @pre_load
    def set_field_session(self, data):
        for value in filter(lambda f: hasattr(f, 'schema'), self.fields.values()):
            value.schema.session = self.session

    @pre_load
    def set_field_partial(self, data):
        for value in filter(lambda f: hasattr(f, 'schema'), self.fields.values()):
            value.schema.partial = self.partial
```

Perhaps this should be added to the docs? Or is there a more elegant solution?

**Comment by sloria** [comment]
Thanks for reporting and for the workaround. I agree this is a usability issue. Let's continue discussion of this in #67
