### ISSUE TITLE
Is include_fk=True an antipattern? If not, why isn't it True by default?

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/marshmallow-sqlalchemy#181]
I have a one to many relationship, where one `User` can have many `Deliveries`. When I create a `Delivery`, I want to `POST /delivery/` with the foreign key user ID in the data `{ user_id: 456 }`.

Now some code, see comments `FOO` and `BAR`:
```
class Delivery(BaseModel):    
    status = db.Column(db.Enum("new", "dispatched", nullable=False))
    # ... (some other Columns)

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

class DeliverySchema(ma.ModelSchema):
    class Meta:
        include_fk = True  # FOO
        model = Delivery
        strict = True

    # UserSchema has deliveries as Nested
    user = ma.HyperlinkRelated("UsersView:get")

delivery_schema = DeliverySchema()

class DeliveriesView(FlaskView):
    @use_kwargs(delivery_schema.fields)
    def post(self, **kwargs):
        # BAR
        print(', '.join(['{}={!r}'.format(k, v) for k, v in kwargs.items()]))
        delivery = Delivery(user_id=kwargs["user_id"])
        db.session.add(delivery)
        db.session.commit()
        return delivery_schema.jsonify(delivery), 201

```

If I don't `include_fk = True`, `kwargs` doesn't contain `user_id`. But how am I supposed to update the field in my database if it doesn't get passed in?

This seems like a common use case, and I assume `include_fk = True` would be the default if it was meant to be used a lot. I feel like I'm missing something, I'm just not sure what.

Alternatively `POST /delivery/456/` works, but as I understand it, it's less preferable to have the new data as part of the URL, and I'm not inclined to work around something in my code that smells off.

Grateful for any help, and happy to provide more information as needed.

**Comment by sloria** [comment]
`include_fk = True` is not an antipattern. My best guess as to why we decided not to make it the default is that `ModelSchema` already autogenerates fields for relationships, so FK fields would be redundant. Often, users want to have FK fields for deserialization but not for serialization. That's very specific though, and I think it would be unintuitive to generate that by default. It's difficult to really know what the "common" use case is...
