### ISSUE TITLE
include_fk = True awkward when foreign key is required (nullable=False)

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/marshmallow-sqlalchemy#182]
This follows on from my question in #181. I guess it might be user error / misunderstanding, but I'd like to share here anyway to get the community's feedback. Take the following example code, similar to that shown in #181 :

```python
class Delivery(BaseModel):    
    status = db.Column(db.Enum("new", "dispatched", nullable=False))
    # ... (some other Columns)

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

class DeliverySchema(ma.ModelSchema):
    class Meta:
        include_fk = True  # FOO
        model = Delivery
        strict = True

    #  user_id = fields.Int(missing=None)  # BAR

    # UserSchema has deliveries as Nested
    user = ma.HyperlinkRelated("UsersView:get")

delivery_schema = DeliverySchema()
deliveries_schema = DeliverySchema(many=True)

class DeliveriesView(FlaskView):

    @use_kwargs(deliveries_schema.fields)
    def index(self, **kwargs):
        deliveries = Delivery.query.filter_by(**kwargs)
        return deliveries_schema.jsonify(deliveries)

    @use_kwargs(delivery_schema.fields)
    def post(self, **kwargs):
        delivery = Delivery(user_id=kwargs["user_id"])
        db.session.add(delivery)
        db.session.commit()
        return delivery_schema.jsonify(delivery), 201
```

`user_id` is defined as `nullable=False`, because technically I should never be able to create a `Delivery` without an associated `User`, which is achieved in `post`. So adding `include_fk=True` (marked above as `FOO`) seemed like the sensible thing to do.

Unfortunately, this broke my call to `index`, which started returning 422 because `user_id` was required. I tried to work round this by adding the line marked above as `BAR`, `user_id = fields.Int(missing=None)`. This passed the 422 validation, but breaks calls to `index` as `user_id` of `None` would be added to the SQL query by webargs, when not explicitly specified as a parameter.

I can work around this by setting `nullable=True` for `user_id`. This implicitly sets `required=False` and hence allows the 422 validation to pass when calling `index`. Yet, it doesn't seem quite right from a business perspective. Is this a feature, in which case how should I express my schema, or is it a bug?

**Comment by sloria** [comment]
I think your use case is met by using `TableSchema` instead of `ModelSchema`.

* You're not deserializing to model objects, so `ModelSchema` is unnecessary.
* You can get rid of the `delivery_schema.fields` hack. With `TableSchema`, you can just pass schema instances to `use_kwargs`.

Here's a working adaptation of your code:

```python
from flask import Flask, jsonify
from flask_classful import FlaskView
from flask_marshmallow import Marshmallow
from flask_sqlalchemy import SQLAlchemy
from marshmallow_sqlalchemy import TableSchema
from webargs.flaskparser import use_kwargs

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///test.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db = SQLAlchemy(app)
ma = Marshmallow(app)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)


class Delivery(db.Model):
    __tablename__ = "delivery"
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Enum("new", "dispatched"), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)


class DeliverySchema(TableSchema):
    class Meta:
        include_fk = True
        table = Delivery.__table__
        strict = True


delivery_schema = DeliverySchema()
deliveries_schema = DeliverySchema(many=True)


class DeliveriesView(FlaskView):
    @use_kwargs(DeliverySchema(exclude=("user_id",))) # or only=('status', ...)
    def index(self, **kwargs):
        deliveries = Delivery.query.filter_by(**kwargs)
        return jsonify(deliveries_schema.dump(deliveries).data)

    @use_kwargs(DeliverySchema())
    def post(self, **kwargs):
        delivery = Delivery(user_id=kwargs["user_id"], status=kwargs["status"])
        db.session.add(delivery)
        db.session.commit()
        return jsonify(delivery_schema.dump(delivery).data), 201


DeliveriesView.register(app)


if __name__ == "__main__":
    db.create_all()
    db.session.add(User())
    db.session.commit()
    app.run(debug=True)
```

**Comment by antgel** [comment]
@sloria Thanks for the answer, I have some of follow-up points as I would like to actually understand what I'm doing rather than cargo-culting. :)

1. Can you elaborate on the use of `TableSchema` vs `ModelSchema`? I got here via the marshmallow-sqlalchemy docs, which don't mention `TableSchema` at all, they only use `ModelSchema`. I am struggling to find examples of `TableSchema` usage on the web. When you say "You're not deserializing to model objects", what *is* the use case for doing that? As I said in private, I didn't get here with (de)serialization first and foremost in my mind, I'm more trying to glue my API to my database, and learning what I need to on the way.
2. I didn't see `TableSchema` in the docs (at least in the Recipes section which is what I mainly read). The only way to know that it exists is by reading the API reference, which by definition is less likely to be read unless you know what you're looking for. Anyway there, the description for both `TableSchema` and `ModelSchema` is "Base class for SQLAlchemy model-based Schemas.", so that also doesn't help me decide what each one is meant for.
3. About adding ` @use_kwargs(DeliverySchema(exclude=("user_id",)))`, would that break any potential `GET` requests if I wanted to use `user_id` in the query string and pass it to `filter_by` to return only Deliveries associated with a specific user?
4. Your comment about the `delivery_schema.fields` hack was also interesting. I remember when I started, so many examples passed the schema instances to `@use_kwargs` and I couldn't work out why this wouldn't work for me. :blush: I guess they weren't using `ModelSchema`...
5. Is `partial=True` in any way helpful or relevant to this use case, or is that for other purposes?

**Comment by sloria** [comment]
> Can you elaborate on the use of TableSchema vs ModelSchema?

`TableSchema` generates fields from SQLA `Table` objects. Therefore, it will not generate fields for relationships, and it will not deserialize to model objects.

> When you say "You're not deserializing to model objects", what is the use case for doing that?

In some cases you want to deserialize to a dictionary instead of a model object. For example, in a PUT or PATCH request, you might want have business logic for updating things that don't map 1:1 to a model object.

> I didn't see TableSchema in the docs

Yeah, we do need to improve the docs for `TableSchema`--just haven't gotten around to it. PRs welcome =)

> About adding @use_kwargs(DeliverySchema(exclude=("user_id",))), would that break any potential GET requests if I wanted to use user_id in the query string 

Yes. If you want to allow user_id as a filter param, then you can use a separate schema or pass a dict to `@use_kwargs`

```python
@use_kwargs(DeliveryQueryArgsSchema, locations=('query',))
def index(....):

# or 

@use_kwargs({"user_id': fields.Int(), "status": fields.Str(...)})
def index(...):
```

> Is partial=True in any way helpful or relevant to this use case, or is that for other purposes?

`partial` is used to temporarily disabled `required` validation, and is most typically used for deserialization in `PATCH` requests.

----

So here's a revised version of the app, now that I think I have a better idea of what you're trying to achieve

```python
from flask import Flask, jsonify
from flask_classful import FlaskView
from flask_marshmallow import Marshmallow
from flask_sqlalchemy import SQLAlchemy
from marshmallow.validate import OneOf
from webargs.flaskparser import use_args, use_kwargs

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///test.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db = SQLAlchemy(app)
ma = Marshmallow(app)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)


class Delivery(db.Model):
    __tablename__ = "delivery"
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Enum("new", "dispatched"), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)


class DeliverySchema(ma.ModelSchema):
    class Meta:
        include_fk = True
        model = Delivery
        strict = True


delivery_schema = DeliverySchema()
deliveries_schema = DeliverySchema(many=True)


class DeliveriesView(FlaskView):
    @use_kwargs(
        {"user_id": ma.Int(), "status": ma.Str(validate=OneOf(("new", "dispatched")))},
        locations=("query",),
    )
    def index(self, **kwargs):
        deliveries = Delivery.query.filter_by(**kwargs)
        return deliveries_schema.jsonify(deliveries)

    @use_args(delivery_schema)
    def post(self, *args, **kwargs):
        # XXX couldn't figure out a way to avoid
        # this with flask-classful...
        delivery = args[0]
        db.session.add(delivery)
        db.session.commit()
        return delivery_schema.jsonify(delivery), 201


DeliveriesView.register(app)


if __name__ == "__main__":
    db.create_all()
    db.session.add(User())
    db.session.commit()
    app.run(debug=True)
```

**Comment by antgel** [comment]
> In some cases you want to deserialize

Did you mean to write more, i.e. in what sort of cases would the user *not* want to deserialize? I naively would have thought I *always* want to deserialize, After all, I get JSON from the API which I then want to use in my code. I note your second code example used `ModelSchema` not `TableSchema` after all. :)

> partial is used to temporarily disabled required validation, and is most typically used for deserialization in PATCH requests.

I use the `.fields` "hack" and `**kwargs` with my `PATCH` request, which I haven't mentioned yet but looks something like this:

```python
    @use_kwargs(delivery_schema.fields)
    def patch(self, _id, **kwargs):
        delivery = Delivery.query.get_or_404(_id)
        for kwarg in kwargs:
            if kwargs[kwarg] is not None:
                delivery.__setattr__(kwarg, kwargs[kwarg])
        db.session.commit()
        return delivery_schema.jsonify(delivery), 200
```

Does this suck? Are you saying that using `@use_args` and removing `.fields` in conjunction with `partial` would be the way forward here? I originally tried [schema factories](https://webargs.readthedocs.io/en/latest/advanced.html#schema-factories) and didn't get very far, but I can go back to it if that's definitely the way forward.

Now some points relating to revised code example:

* Passing the explicit dict to `@use_kwargs` seems like a lot of repitition, given that the schema was already defined. Is this an unavoidable price for setting `user_id` to `nullable=False`?
* The other issue with the explicit dict is the addition of `"user_id": ma.Int()`. Won't this break `GET`s when `user_id` isn't provided? I want to be able to `GET /deliveries/`, and *optionally* include query string parameters to pass to `filter_by()`.
* Why is the `args` change in `post()` preferable to my original `@use_kwargs(delivery_schema.fields)` "hack"? I might be answering myself, but I can see that it's quite nice not to have to explicitly specify the obvious mapping of `status` and `user_id` in `add()`.
* Aside: The [webargs docs](https://webargs.readthedocs.io/en/latest/advanced.html#marshmallow-integration) show examples of `Schema`s being passed to both `@use_args` and `@use_kwargs`. I guess `ModelSchema` is an exception? Is that documented anywhere? If not, where should it be? I could submit a PR to clarify that.
* I guess this gets into `@use_args` vs `@use_kwargs` territory. In examples online, `@use_kwargs` is more common, so I (possibly wrongly) assumed that it is generally a better fit / more flexible / whatever. But not I think about it, it's not clear when one is preferable to the other.

Thanks for your patience, I believe I'm learning a lot, and hopefully the thread will help others in the future.

**Comment by sloria** [comment]
> Did you mean to write more,

Yes, not sure what happened there. Edited my previous comment.

> removing .fields in conjunction with partial would be the way forward here?

Yeah, that's the more on-rails way to handle it, but I guess you'd still need to figure out a way do the `get_or_404` logic instead of marshmallow-sqlalchemy's default behavior. So maybe the .fields thing isn't so bad.

>  seems like a lot of repitition, given that the schema was already defined.

You could also use a schema inheritance to DRY things up a bit. Up to you.

> I guess ModelSchema is an exception?

Schemas that deserialize to objects won't work with `use_kwargs`. There's a note about it here: https://webargs.readthedocs.io/en/latest/advanced.html#marshmallow-integration

> Any Schema passed to use_kwargs MUST deserialize to a dictionary of data. Keep this in mind when writing post_load methods.

**Comment by sloria** [comment]
By the way, I've opened an issue to add an option to allow ModelSchema to deserialize to a dictionary, which could obviate the `.fields` hack: https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/193

**Comment by sloria** [comment]
Closing this for now.
