### ISSUE TITLE
add section to docs about using with Flask

### ISSUE THREAD

**Issue by twosigmajab** [marshmallow-code/marshmallow-sqlalchemy#196]
Was curious if there was a recommendation for folks already using (1) Flask-SQLAlchemy, and (2) Marshmallow (e.g. via some Flask extension that uses Marshmallow for Swagger integration), who then wanted a way to de-duplicate between their Marshmallow schemas and SQLAlchemy models and found their way to this project. Searching the docs for Flask doesn't currently turn up [any results](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/search.html?q=flask&check_keywords=yes&area=default). Since it's not immediately clear how to best integrate Flask, SQLAlchemy, and Marshmallow -- (there exist Flask-Marshmallow, Flask-SQLAlchemy, and Marshmallow-SQLAlchemy, but no Flask-Marshmallow-SQLAlchemy) -- would it be worth adding at least a sentence or two for beginners with some guidance here?

Thanks for your consideration and for maintaining so many great projects!

**Comment by sloria** [comment]
Flask-Marshmallow integrates with marshmallow-sqlachemy. See  the "Optional Flask-SQLAlchemy Integration" section here: https://flask-marshmallow.readthedocs.io/en/latest/

**Comment by twosigmajab** [comment]
Thanks @sloria, that was easy to miss perusing the three projects, but once you pointed it out, I quickly got Flask, Marshmallow, and SQLAlchemy all working together beautifully!

On a related note, if a user is using Marshmallow-SQLAlchemy, is your answer to the question in marshmallow-code/marshmallow#704 ("How to use it with templates like WTForms?") any different? e.g. Do you recommend using one of the WTForms-SQLAlchemy integrations[1,2] to get Marshmallow+SQLAlchemy+auto-generated forms all working together nicely? 

[1] https://github.com/wtforms/wtforms-sqlalchemy
[2] https://github.com/kvesteri/wtforms-alchemy

**Comment by sloria** [comment]
Great, glad you got things working. 

As for generating forms, I'm not sure what the state of the art is since I've not had that use case recently. So I can't really give a recommendation.
