### ISSUE TITLE
Fields nested create new records in database

### ISSUE THREAD

**Issue by gomes-fdr** [marshmallow-code/marshmallow-sqlalchemy#200]
Hello friends,
I am using fields nested with data coming from a json in a rest API.

Why does whenever I do a POST of json, where do I use 'fields.Nested' a new record is created in the table of the nested object?

Here's an example of how my code is:

```
class PerfilSchema(ma.ModelSchema):
    id = fields.Integer(dump_only=True)
    descricao = fields.Str()
    permissao = fields.Int()
    
    class Meta:
        model = Perfil
        fields = ('id', 'descricao', 'permissao')

class SituacaoSchema(ma.ModelSchema):
    id = fields.Integer(dump_only=True)
    descricao = fields.Str()
    
    class Meta:
        model = Situacao
        fields = ('id', 'descricao')


class ProfissionalSchema(ma.ModelSchema):
    perfil = fields.Nested(PerfilSchema)
    situacao = fields.Nested(SituacaoSchema)

    class Meta:
        model = Profissional
```
Every time I insert a 'Profissional' via API, a new record is inserted in the 'Perfil' table and in the 'Situacao' table too.

Do I need a separate search for these situations?

**Comment by sloria** [comment]
ModelSchema will deserialize to a new instance of your model, so a new `Perfil` record will be created. You may want to try `marshmallow_sqlalchemy.fields.Related` instead of `Nested`.

**Comment by gomes-fdr** [comment]
I am using flask marshmallow, do you know if there is 'Related' option? I didn't find it.
(marshmallow-sqlalchemy==0.16.1, flask-marshmallow==0.10.0, marshmallow==2.19.1)

Many thanks for the reply!

**Comment by sloria** [comment]
```python
from marshmallow_sqlalchemy.fields import Related
```

**Comment by gomes-fdr** [comment]
I have another issues in my code, now I receive `KeyError: <class 'backend.serealizer.PerfilSchema'>`
I'll keep working around here, thanks for now.

**Comment by sloria** [comment]
OK, closing this for now. Feel free to comment if you run into further issues with this.

**Comment by duckbytes** [comment]
Sorry for reopening an old issue but I have this same problem. I'm trying to figure out how to update a nested field without creating a new entry in the database. If I use Related I get a similar KeyError as above.

Was a solution ever found for this?
