### ISSUE TITLE
A few type of columns were neglected when building Schema from SQLAlchemy model.

### ISSUE THREAD

**Issue by wtkmn** [marshmallow-code/marshmallow-sqlalchemy#204]
Hi, let me share my problem.

When I try to build schema from SQLAlchemy model (or Table), a few columns with specific property were neglected.

The columns didn't reflect in schema were one of
* DateTime
* INTEGER (mysql dialect)

I would like to know if this is a bug or not.

**Comment by sloria** [comment]
AFAIK the omissions were not intentional. Feel free to send a PR

**Comment by sloria** [comment]
Fixed in 0.20.0
