### ISSUE TITLE
Imcompatibility with marshmallow-3.0.0rc6

### ISSUE THREAD

**Issue by jssuzanne** [marshmallow-code/marshmallow-sqlalchemy#208]
With the latest version of marshmallow a get the error:

> ImportError while loading conftest '/home/jssuzanne/anyblok/AnyBlok_Marshmallow/anyblok_marshmallow/tests/conftest.py'.
anyblok_marshmallow/__init__.py:10: in <module>
    from .schema import SchemaWrapper, PostLoadSchema  # noqa
anyblok_marshmallow/schema.py:10: in <module>
    from marshmallow_sqlalchemy.schema import (
venv/lib/python3.6/site-packages/marshmallow_sqlalchemy/__init__.py:4: in <module>
    from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
venv/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py:3: in <module>
    from marshmallow.compat import with_metaclass, iteritems
E   ModuleNotFoundError: No module named 'marshmallow.compat'

**Comment by sloria** [comment]
@jssuzanne What version of marshmallow-sqlalchemy are you using? 0.16.3 is expected to be compatible with marshmallow 3.0.0rc6.

**Comment by sloria** [comment]
Closing for now. Let me know if you're still having issues on the latest 0.16.3 release.

**Comment by jssuzanne** [comment]
Sorry @sloria , 

I have not seen the answer before.

You are rigth, I was on the version **0.16.2**. On the latest version it is works.

Thanks
