### ISSUE TITLE
Question: using render_module in Meta

### ISSUE THREAD

**Issue by javiersanp** [marshmallow-code/marshmallow-sqlalchemy#209]
Is there any way to use [render_module](https://marshmallow.readthedocs.io/en/3.0/api_reference.html?highlight=render_module) option of marshmallow Schema Meta class to serialize with a module different of json from the standard library?

**Comment by sloria** [comment]
Yes, the `render_module` option should be working fine with this library. Are you running into an issue with it?

**Comment by javiersanp** [comment]
You are right, but I had to use 'json_module' instead of 'render_module'. My versions: 
marshmallow            2.19.2 
marshmallow-sqlalchemy 0.16.3
The parameter rename occurs in version 3.0.0, so every thing is ok. Thanks.

**Comment by ecke101** [comment]
I don't really know how this works but is there no way to use render_module with dump()? Right now I have to do simplejson.loads(obj_schema.dumps(obj)) but if there's no decimal field I can do just obj_schema.dump(obj)
