### ISSUE TITLE
Declarative configuration

### ISSUE THREAD

**Issue by dpwrussell** [marshmallow-code/marshmallow-sqlalchemy#21]
Another idea that is [straight from ColanderAlchemy](http://colanderalchemy.readthedocs.org/en/latest/customization.html#configuring-within-sqlalchemy-models).

I believe this could be implemented relatively easily, but there are numerous different ways one could go about it, so I think perhaps some discussion is more appropriate than forging ahead with a PR which might turn out not to be the best way at all.

I would be really nice to be able to do something like this:

``` python
    id = Column(Integer,
                primary_key=True,
                info={
                    'marshmallow_sqlalchemy': {
                        'dump_only': False
                     }
                })
```

These would then be processed when constructing the schemas to override the settings. Potentially anything that marshmallow can do could be declared there.

I hacked this in quickly:

``` python
    def _add_column_kwargs(self, kwargs, column):
        """Add keyword arguments to kwargs (in-place) based on the passed in
        `Column <sqlalchemy.schema.Column>`.
        """
        if column.nullable:
            kwargs['allow_none'] = True

        if hasattr(column.type, 'enums'):
            kwargs['validate'].append(validate.OneOf(choices=column.type.enums))

        # Add a length validator if a max length is set on the column
        if hasattr(column.type, 'length'):
            kwargs['validate'].append(validate.Length(max=column.type.length))

        if hasattr(column.type, 'scale'):
            kwargs['places'] = getattr(column.type, 'scale', None)

        # Primary keys are dump_only ("read-only")
        if getattr(column, 'primary_key', False):
            kwargs['dump_only'] = True

        if 'marshmallow_sqlalchemy' in column.info:
            settings = column.info['marshmallow_sqlalchemy']

            if 'dump_only' in settings:
                kwargs['dump_only'] = settings['dump_only']

            if 'load_only' in settings:
                kwargs['load_only'] = settings['load_only']
```

and it worked quite well. It didn't support inheritance though which we definitely should I think. That can be achieved relatively easily as well I think as we have for each property, the list of applicable columns, so we just need to iterate over them in order from super to sub and apply the settings found in info to provide ordinary inheritance override behaviour. I think the same thing could be applied to relationships as well.

Thoughts?

**Comment by sloria** [comment]
This has been added in 0.15.0.
