### ISSUE TITLE
deserializion difficulties: schema.load(data) only works, when it returns model.__dict__

### ISSUE THREAD

**Issue by hiphamster** [marshmallow-code/marshmallow-sqlalchemy#226]
Hi,
Unless i explicitly return a ```dict``` from the ```load_subcontractor``` method (schema.py, see below) I get "Subcontractor object missing 'get' attribute", but based on the [documentation](https://marshmallow.readthedocs.io/en/2.x-line/quickstart.html#deserializing-objects-loading) i should just return a model object:
```
from marshmallow import Schema, fields, post_load

class UserSchema(Schema):
    name = fields.Str()
    email = fields.Email()
    created_at = fields.DateTime()

    @post_load
    def make_user(self, data):
        return User(**data)
```
What gives?
**Here's the setup of my flask application:**

app/__init__.py:
```
 18 db = SQLAlchemy()
 19 ma = Marshmallow()
...
 27 def create_app(config_name=None):
...
 50     db.init_app(app)
 51     ma.init_app(app)
...
101     return app
```
app/models.py
```
311 class Subcontractor(db.Model):
312     """
313     A cleaning service provider
314     """
315     __tablename__ = 'subcontractors'
316
317     id = db.Column(db.Integer, primary_key=True)
318     # site_id = db.Column(db.Integer, db.ForeignKey('sites.id'))
319     name = db.Column(db.String(50), unique=True)
320     phone = db.Column(db.String(20), index=True, unique=True)
321     # email = db.Column(db.String(60), index=True, unique=True)
322     fax = db.Column(db.String(20), index=True, unique=True)
323     street = db.Column(db.String(150), index=True)
324     city = db.Column(db.String(50))
325     state = db.Column(db.String(2))
326     zip = db.Column(db.String(30))
```
app/api/schema.py
```
  1 from .. import models, ma, db
  2 from marshmallow import fields, post_load, pre_load
  3 from flask import current_app
...
 58 class SubcontractorSchema(ma.ModelSchema):
 59     class Meta:
 60         include_fk = True
 61         model = models.Subcontractor
 62         strict = True
 63
 64     @post_load
 65     def load_subcontractor(self, data):
 66         s = models.Subcontractor()
 67         s.name = data.get('name', None)
 68         s.phone = data.get('phone', None)
 69         s.fax = data.get('fax', None)
 70         s.street = data.get('street', None)
 71         s.city = data.get('city', None)
 72         s.state = data.get('state', None)
 73         s.zip = data.get('zip', None)
 74
 75         db.session.add(s)
 76         db.session.commit()
 77
 78         return s.__dict__
 79
...
```
app/api/resource.py (blueprint)
```
...
237     def post_collection(self, *args, **kwargs):
238         current_app.logger.debug('post_collection')
239
240         data = request.get_json()
241
242         resource_schema = self.resource_schema()
243
244         # pdb.set_trace()
245
246         resource, errors = resource_schema.load(data, transient=False)
247         current_app.logger.debug('resource: {}\nerrors: {}'.format(resource, errors))
248
249         return 'OK'
...
```

**Comment by sloria** [comment]
`ModelSchema` already has a `post_load` method that returns a model instance:
https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/ad4b0ec9d48149af08c1d7b2ee9498d570cbcdda/src/marshmallow_sqlalchemy/schema.py#L184-L201

So your `load_subcontractor` is receiving a model instance rather than a dictionary. If you're just trying to deserialize an instance and add to the db, you can probably just remove your `load_subcontractor` method.

```python
subcontractor = SubcontractorSchema().load(data, transient=True).data
db.session.add(subcontrator)
```

**Comment by hiphamster** [comment]
Thank you for a quick response. I checked, and ```load_subcontractor``` receives a dict, not an object, but after removing it completely,  my code works. I'm still a bit unclear as to why i didn't need to provide smth like ```load_subcontractor```, and what would be an instance where I'd have to.
Thanks again!

**Comment by sloria** [comment]
My guess is that load_contractor would sometimes receive a `dict`, sometimes not, because the invocation order of post_load methods is not guaranteed. See https://marshmallow.readthedocs.io/en/3.0/extending.html#pre-post-processor-invocation-order.

You don't need `load_subcontractor because you're using `ModelSchema`, which provides a post-load method out-of-box that instantiates a model object.
