### ISSUE TITLE
schema.load might raise exception if database is locked

### ISSUE THREAD

**Issue by Obbi89** [marshmallow-code/marshmallow-sqlalchemy#228]
If the model/schema has relationships that get loaded from database and the database is currently locked due to other parallel operations (multiple parallel requests) the operation fails with an Exception.

It should at least be documented as caveat; if you use SQLite this issue is quite common.

**Comment by sloria** [comment]
Feel free to send a PR adding a note in the docs, but this isn't really specific to marshmallow-sqlalchemy; this is always concern when loading data.
