### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ordered'

### ISSUE THREAD

**Issue by bzaks1424** [marshmallow-code/marshmallow-sqlalchemy#235]
So I'm using the following:
marshmallow (3.0.0)
marshmallow-sqlalchemy (0.17.0)
psycopg2 (2.8.3)
SQLAlchemy (1.3.7)

I've got the following:
_Tables.py
```
person_table = Table(
    'person',
    Base.metadata,
    Column('id', UUID(as_uuid=True), primary_key=True, nullable=False, default=sqlalchemy.text('uuid_generate_v4()'), server_default=sqlalchemy.text('uuid_generate_v4()')),
    Column('display_name', String(length=255), nullable=False),
    Column('email', String(length=255), unique=True, nullable=False),
    Column('first_name', String(length=255), nullable=False),
    Column('image', Text),
    Column('last_name', String(length=255), nullable=False),
    Column('phash', Text))
```

SAObjects.py
```
class Person(Base):
    def __repr__(self):
        return (
            "<Person id='" + str(self.id)
            + "' first_name='" + self.first_name
            + "' last_name='" + self.last_name + "'>")
    __table__ = person_table
```

_Schema.py
```
class BaseOpts(ModelSchemaOpts):
    def __init__(self, meta):
        if not hasattr(meta, "sqla_session"):
            meta.sqla_session = SqlSessionSingleton.get_instance()
        super(BaseOpts, self).__init__(meta)

class BaseSchema(ModelSchema):
    OPTIONS_CLASS = BaseOpts

class PersonSchema(BaseSchema):
    class Meta:
        model = Person
```

but I am getting the following:
```
$ python3 db_tester.py
Traceback (most recent call last):
  File "db_tester.py", line 4, in <module>
    from ._Schema import PersonSchema
  File "#####-venv/myproject/tests/myproject/_Schema.py", line 21, in <module>
    class BaseSchema(ModelSchema):
  File "#####-venv/lib/python3.7/site-packages/marshmallow/schema.py", line 112, in __new__
    klass.opts = klass.OPTIONS_CLASS(meta, ordered=ordered)
TypeError: __init__() got an unexpected keyword argument 'ordered'
```

Did I screw something up?

**Comment by sloria** [comment]
Your `BaseOpts` constructor needs to accept `ordered` or `*args, **kwargs`.

```python
class BaseOpts(ModelSchemaOpts):
    def __init__(self, meta, ordered=False):
        if not hasattr(meta, "sqla_session"):
            meta.sqla_session = SqlSessionSingleton.get_instance()
        super(BaseOpts, self).__init__(meta, ordered=ordered)
```

**Comment by bzaks1424** [comment]
Could you please add this to your https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#base-schema-ii 
Just as a person who is brand new to this - I had no idea where to look.

**Comment by bzaks1424** [comment]
Also - "ordered" is undefined in this instance - do I need to set that from somewhere?

**Comment by sloria** [comment]
Ah yes, looks like the doc is incorrect. Sorry about that. I'll fix it later. Or feel free to send a PR if you're feeling generous =)

**Comment by bzaks1424** [comment]
Alright, I've updated your code on there. Now I just need to learn how to do the push / PR... do you have a doc to point me at there? (I'm really sorry - I'm *really* new at this.

**Comment by sloria** [comment]
No worries. See https://opensource.guide/how-to-contribute/#opening-a-pull-request for a guide on sending a PR. You'll need to fork this repo, (locally) create a new branch with your edits (`git checkout -b fix-docs`), push your branch (`git push origin fix-docs`, assuming your fork is `origin`), then send a PR through the GitHub UI (big green button)

**Comment by frankcash** [comment]
how would one do this without creating a shared base model
