### ISSUE TITLE
Update documentation for marshmallow 3.0.0

### ISSUE THREAD

**Issue by mathiasritter** [marshmallow-code/marshmallow-sqlalchemy#236]
**marshmallow 3.0.0** was released [yesterday](https://marshmallow.readthedocs.io/en/stable/changelog.html#id1).

Please update the documentation of marshmallow-sqlalchemy for this new release.

**Example**
`schema.load(data)` no longer returns `UnmarshalResult` with the deserialized object stored under the attribute `data`. Instead, it returns the deserialized object directly without wrapping it in `UnmarshalResult`.
Therefore, the following line in [this example ](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/#de-serialize-your-data) needs to be changed from:
`load_data = author_schema.load(dump_data, session=session).data`
to
`load_data = author_schema.load(dump_data, session=session)`

I'm assuming that there are other changes as well that need to be reflected in the documentation.

**Comment by sloria** [comment]
Yeah, this is on my todo list. Not sure I'll be able to get to it today, though. I'd gladly review and merge a PR!
