### ISSUE TITLE
Drop Python 2 and 3.5 support

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow-sqlalchemy#241]
* py2 EOL is nigh
* marshmallow 3 no longer supports Python 2
* Very few marshmallow users use Python 3.5 (even fewer than Python 2): http://marshmallow.sloria.io/#ma2-vs-ma3-pyminor

**Comment by mgasner** [comment]
Just FYI, this broke Apache Airflow on py2 and 3.5

**Comment by AbdealiLoKo** [comment]
Apache airflow doesn't seem to be using this library from what I can see in their setup.py
https://github.com/apache/airflow/blob/1b1d79c0a67ba5a41efefe1a6d8df4c335869b43/setup.py

**Comment by mgasner** [comment]
Apache Airflow has a transitive dependency through Flask-AppBuilder, see https://github.com/dpgaspar/Flask-AppBuilder/pull/1111 and https://issues.apache.org/jira/browse/AIRFLOW-5430. This is a major breaking change and it would be courteous to bump the major version.

**Comment by AbdealiLoKo** [comment]
To be honest, I'm not too sure it warrants a major version change.
Projects like pandas and numpy are in a similar boat and have not changed major versions to drop py2 support. 
Obviously this opinion differs from project to project, and person to person.

In my opinion minor version bump should be sufficient with an appropriate changelog.
But other maintainers should probably comment too.

**Comment by mgasner** [comment]
It's pragmatic -- many of your downstream dependencies, like airflow, are pinned to `<1.0.0`, expecting that breaking changes will come with a major version bump.

**Comment by sloria** [comment]
> many of your downstream dependencies, like airflow, are pinned to <1.0.0, expecting that breaking changes will come with a major version bump.

Per semver, users should expect breaking changes for middle version number bumps because this is _pre-1.0_. So it's incorrect to pin to `<1.0.0`.  To allow for patches, you should use e.g. `~=0.18.0` or `>=0.18.0,0.18.*`.
