### ISSUE TITLE
AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'

### ISSUE THREAD

**Issue by HarmeetSokhi** [marshmallow-code/marshmallow-sqlalchemy#249]
Hi ,

After today's release we are getting the below error when starting the airflow server.We are using amazon-linux-extras install postgresql10=10

"Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 22, in <module>
    from airflow.bin.cli import CLIFactory
  File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 69, in <module>
    from airflow.www_rbac.app import cached_app as cached_app_rbac
  File "/usr/local/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 24, in <module>
    from flask_appbuilder import AppBuilder, SQLA
  File "/usr/local/lib64/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .base import AppBuilder
  File "/usr/local/lib64/python3.6/site-packages/flask_appbuilder/base.py", line 5, in <module>
    from .api.manager import OpenApiManager
  File "/usr/local/lib64/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 11, in <module>
    from marshmallow_sqlalchemy.fields import Related, RelatedList
  File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
    from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
  File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 3, in <module>
    from .convert import ModelConverter
  File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 36, in <module>
    class ModelConverter:
  File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 52, in ModelConverter
    postgresql.MONEY: fields.Decimal,
AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'

**Comment by daaain** [comment]
We have a similar issue where just doing an import breaks our app:

```
...
  File "/usr/local/lib/python2.7/site-packages/basis_utils/geo/utils.py", line 9, in <module>
    from marshmallow_sqlalchemy import ModelConverter
  File "/usr/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
    from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
  File "/usr/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/schema.py", line 101
    class TableSchema(ma.Schema, metaclass=TableSchemaMeta):
```

**Comment by sloria** [comment]
@HarmeetSokhi What version of sqlalchemy are you using? 0.19.0 bumps the minimum sqlalchemy version to 1.2.0. I recommend upgrading (1.2.0 is nearly 2 years old). If that's not feasible, you will need to pin to marshmallow-sqlalchemy==0.18.0.

@daaain I see that you're using Python 2.7. 0.19.0 drops support for Python 2.7 and 3.5. If you're  using those versions, you need to either upgrade your Python or pin to  marshmallow-sqlalchemy==0.18.0.

**Comment by sunilplivo** [comment]
@sloria We're facing this same issue in our production server too. We're using `python:3.6-slim` docker image as base image. How can we resolve this?

**Comment by sloria** [comment]
@sunilplivo What versions of sqlalchemy and marshmallow are you using?

**Comment by sunilplivo** [comment]
sqlalchemy - 1.1.18
marshmallow-sqlalchemy - 0.17.2

**Comment by sloria** [comment]
@sunilplivo See above https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/249#issuecomment-528839289

**Comment by sloria** [comment]
In the future, please review the changelog before upgrading and posting issues (this is generally a good practice for all dependencies!). This change was [clearly documented](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/changelog.html).

> 0.19.0 (2019-09-05)
> 
> * Drop support for Python 2.7 and 3.5 (#241).
> * Drop support for marshmallow<2.15.2.
> * Only support sqlalchemy>=1.2.0.

The minimum SQLAlchemy version was raised to reduce the maintenance burden of supporting very old SQLA versions. 1.2.0 is nearly 2 years old, so it seemed a reasonable change. If you reeeally need support for SQLA<1.2.0 feel free to send a PR reverting https://github.com/marshmallow-code/marshmallow-sqlalchemy/pull/247

**Comment by sloria** [comment]
Also, two recommendations:

1) If you're developing a library, make sure to correctly specify versions for pre-1.0 dependencies. Per semver, pre-1.0 libraries may introduce breaking changes with a _middle version bump_. So be sure to use e.g. `marshmallow-sqlalchemy~=0.18.0` (not `>=0.18.0,<1.0.0`).
2) If you're developing an application, pin _all_ of your dependencies (not just top-level dependencies) using pip-compile, poetry, or pipenv.

**Comment by daaain** [comment]
@sloria thanks for the clarification, my problem was that the project is on Python 2.7.

If you have a minute it would be great if these version requirements were implemented with a warning and not just in the changelog. I have Pip 19, so if there was `python_requires` etc set up I would have got a warning and not just a runtime error. Please see https://python3statement.org/practicalities/ for more info.

**Comment by daaain** [comment]
Also, for the benefit of people who don't directly use this library: you can still pin the version, just put it in your `Pipfile` above the dependency which needs it, for example if you use `flask-marshmallow`:

```toml
marshmallow-sqlalchemy="~=0.18.0"
flask-marshmallow="*"
```

**Comment by sloria** [comment]
I've added `python_requires=>=3.6`. Thanks for the suggestion @daaain
