### ISSUE TITLE
Ignore `nullable` property of column in generated fields

### ISSUE THREAD

**Issue by connebs** [marshmallow-code/marshmallow-sqlalchemy#252]
In marshmallow, objects are assumed to be valid, so no validation is done on `dump`. Validation is only performed on `load`. A marshmallow `load` generally goes hand-in-hand with inserting something into the DB in SQLAlchemy. However, the `nullable` property on a column is referring to the fact that in your database, you want that column to always have something in it, e.g. it is already validating that property on insert (load).

I'm doing a terrible job of explaining this, but essentially I think that marshmallow-sqlalchemy automatically assuming I want my `nullable=False` columns to be `required=True` in my marshmallow Schema is redundant (because my DB will already throw an error if a `nullable=False` column is empty) and counter to many (most?) use-cases, where you want to only include selected fields, but not necessarily force non-nullable columns to be in the serialized data that you want to deserialize.

It would be nice if there was at least a way to disable automatically setting `nullable=False` columns to `Field(required=True)` without having to override a bunch of methods in the `ModelConverter`.

**Comment by connebs** [comment]
To give a more concrete use-case of why this is bothering me, say I have a model with some `nullable=False` column, like so:

```
class Person(db.Model):
    name = db.Column(db.String, nullable=False)
    age = db.Column(db.String)
    occupation = db.Column(db.String)
```

I then automatically generate a Schema with marshmallow-sqlachemy:

```
class PersonSchema(ModelSchema):
    class Meta:
        model = Person
        dump_only = ["name"]
```

Now, obviously because I've set `name` to be dump_only, I don't want / need to see it in serialized data that I'm loading. But because I have `nullable=False` on my `name` column, this:

```
PersonSchema().load({"age": 32, "occupation": "farmer"})
```

throws a validation error because `name` is required in the Schema.

**Comment by sloria** [comment]
Hm, this looks like a possible bug. Dump-only fields should not go through 'required' validation. This is working with a plain schema

```python
from marshmallow import Schema, fields


class PersonSchema(Schema):
    name = fields.Str(required=True)

    class Meta:
        dump_only = ["name"]


print(PersonSchema().load({})) # => {}
```

What version of marshmallow and marshmallow-sqlalchemy are you using?

**Comment by connebs** [comment]
Hmm. Using the most up-to-date versions:

```
marshmallow==3.0.1
marshmallow-sqlalchemy==0.17.0
```

**Comment by sloria** [comment]
Thanks. I don't have time to dig into the `dump_only` bug right now. Would definitely welcome a PR if you have the time.

I think generating required fields for non-nullable fields is the correct behavior, though. `nullable=False` means that clients must provide a value on insert, so marshmallow should do that validation. For updates where you don't expect the values to be provided, you should use the `partial` parameter.

**Comment by connebs** [comment]
Argh, no, I'm an idiot, thanks for pointing me in the right direction for debugging. 

I was subclassing `PersonSchema` and overriding the `Meta` class, which was obviously causing the `dump_only` class variable to go *\*poof*\*. I wish sub-classing caused the Meta class to be merged somehow rather than just overwritten, but that's obviously not how classes work. Oh well.

Sorry for the distraction.

**Comment by sloria** [comment]
Oh ok, glad you found the issue.

I often wonder whether we should automagically merge the `Meta` classes. This is an easy thing to trip on.

**Comment by connebs** [comment]
I would probably be in favor of that in a major version bump.

Slight addendum / question - I know about `partial`, but the issue I'm *really* having is that I am using Schema nesting in conjunction with a Model-derived Schema that I would actually like to **subclass** (whew).

So I'm doing this:

```python
# currently unused for the 'Put' schemas, but I'd like to subclass it
class PersonSchema(BaseModelSchema)
    class Meta:
        model = Person
        exclude = [...]
        dump_only = ["name"]

class PutPersonSchema(BaseModelSchema): # <- want to subclass PersonSchema here
    class Meta:
        model = Person
        exclude = ["id"]
        dump_only = ["name"]

class PutVillage(BaseModelSchema):
    person = ma.Nested("PutPersonSchema", many=True)
    class Meta:
        model = Village
```

But I'd really like to be able to sub-class `PersonSchema` from `PutPersonSchema` and just specify `partial`, `exclude`, `dump_only`, etc. without having to re-specify the model or anything I've already specified.

**Comment by sloria** [comment]
```python
class PersonSchema(BaseModelSchema):
    class Meta(BaseModelSchema.Meta):
        model = Person
        # ...

class PutPersonSchema(PersonSchema):
    class Meta(PersonSchema.Meta):
        exclude = ...
```

Does that not work?

**Comment by connebs** [comment]
Generally yes, that's a pretty good solution. I just have a bunch of little things which I want to magically happen as well, haha. 

Thanks again for all the help
