### ISSUE TITLE
Renaming autogenerated fields results in field collision

### ISSUE THREAD

**Issue by aberres** [marshmallow-code/marshmallow-sqlalchemy#286]
According to the [documentation](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#overriding-generated-fields) the following should work to rename the 'name' column to 'custom_name'.

```
class AuthorSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Author
        include_relationships = True
        load_instance = True

class AuthorSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Author
        include_relationships = True
        load_instance = False

    custom_name = auto_field('name')
```

In practice instantiating the schema results in
```ValueError: The attribute argument for one or more fields collides with another field's name or attribute argument. Check the following field names and attribute arguments: ['name']```

When checking `_declared_fields` I found the following keys, including the duplicated name: `['custom_name', 'id', 'name']`

**Comment by sloria** [comment]
The issue is that there are two keys (`name` and `custom_name`) that load into the same attribute (`name`), and it's not clear what should happen if both `name` and `custom_name` appeared in the input to `load`.

If you want both `custom_name` and `name` to appear in the serialized output, uou should make one of them dump-only.

```python
class AuthorSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Author

    custom_name = auto_field("name", dump_only=True)
```

If you want only `custom_name` then you should exclude `name`:

```python
class AuthorSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Author
        exclude = ("name",)

    custom_name = auto_field("name")
```

**Comment by aberres** [comment]
Steven, thanks for the quick reply.

Adding the field to `exclude` is working as you describe.

As what I tried is described in the [documentation](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#overriding-generated-fields) the need to pass `exclude` should be mentioned there, shouldn't it? With what is described right now one does not get a valid schema at all.

Maybe the `ModelConverter` could additionally be tweaked to (optionally) automatically skip the field?

**Comment by aberres** [comment]
Ok, war rereading the docs. I have to admit that `dump_only` is passed there. So we get a valid model.

Soi the question is more: Are the implications clear from the docs or not.

**Comment by sloria** [comment]
I added usage of `exclude` to the docs example: https://github.com/marshmallow-code/marshmallow-sqlalchemy/commit/0df664202e2ea2f010ef25234fcd5bf0a573f076 . Hopefully that clarifies things a bit. Open to docs PRs if you think we can clarify further.
