### ISSUE TITLE
Recipe: Smart Nested Field - possible typo in example

### ISSUE THREAD

**Issue by BorysekOndrej** [marshmallow-code/marshmallow-sqlalchemy#291]
Hi, while looking through the documentation for another issue, I've notice that one of the recipes might have small typo. It's trying to add and commit variable `author`, which is not defined in the example. On the other hand, adding and commiting variable `book` would make perfect sense. So it's just a typo I think.

https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#smart-nested-field

Current version of the relevant part:
```python
book = Book(id=1)
book.author = Author(name="Chuck Paluhniuk")
session.add(author)
session.commit()
```
Suggested version:
```python
book = Book(title="Fight club")
book.author = Author(name="Chuck Paluhniuk")
session.add(book)
session.commit()
```

**Comment by sloria** [comment]
Good catch. It's fixed now
