### ISSUE TITLE
Autogenerating Nested fields by SQLAlchemyAutoSchema

### ISSUE THREAD

**Issue by BorysekOndrej** [marshmallow-code/marshmallow-sqlalchemy#292]
Hi, I'm looking through the new SQLAlchemyAutoSchema and I'm failing to find a way to autogenerate Nested fields based on relationship. Even with `include_relationships = True` the generated fields appear to be `fields.Related`, not `fields.Nested` as I would have guessed. The autogenerating schemas will certainly cleanup my code quite a lot and having the option to generate Nested fields directly would be nice to have. Is such a feature considered? Or is it already included and I'm missing something?

Here's a a fully runnable example showing the different behavior between schema generated by SQLAlchemyAutoSchema and one with manually added field `author = fields.Nested(AuthorSchema)`. I'm primarily looking for the output of the nested version.
```python
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, joinedload
from sqlalchemy import Column, Integer, String, ForeignKey
from marshmallow_sqlalchemy import SQLAlchemyAutoSchema, auto_field, fields

engine = create_engine('sqlite:///test5.db', echo=False)
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()

class Author(Base):
    __tablename__ = 'authors'
    id = Column(Integer, primary_key=True)
    name = Column(String(255))

class Book(Base):
    __tablename__ = 'books'
    id = Column(Integer, primary_key=True)
    title = Column(String(255))
    author_id = Column(Integer, ForeignKey("authors.id"))
    author = relationship("Author", backref="books")

Base.metadata.create_all(engine)

class AuthorSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Author
        load_instance = True
        include_relationships = True

class BookSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = Book
        load_instance = True
        include_relationships = True

class BookSchemaWithNested(SQLAlchemyAutoSchema):
    class Meta:
        model = Book
        load_instance = True
        include_relationships = True

    author = fields.Nested(AuthorSchema)

author = Author(name="Chuck Paluhniuk")
book = Book(title="Fight Club", author=author)
session.add(author)
session.add(book)
session.commit()

print(AuthorSchema().dump(author)) # {'books': [1], 'name': 'Chuck Paluhniuk', 'id': 1}
print(BookSchema().dump(book)) # {'id': 1, 'title': 'Fight Club', 'author': 1}
print(BookSchemaWithNested().dump(book)) # {'id': 1, 'title': 'Fight Club', 'author': {'books': [1], 'name': 'Chuck Paluhniuk', 'id': 1}}

book = session.query(Book).options(joinedload("author")).get(1)
print(BookSchema().dump(book)) # {'id': 1, 'title': 'Fight Club', 'author': 1}

print(BookSchema._declared_fields["author"]) # <fields.Related(default=<marshmallow.missing>, ...
print(BookSchemaWithNested._declared_fields["author"]) # <fields.Nested(default=<marshmallow.missing>, ...
```

**Comment by sloria** [comment]
`Nested` schemas should be declared explicitly, as you've done in `BookSchemaWithNested` above. This is by design, and allows the most flexibility when nesting.

**Comment by mato2000** [comment]
So, when calling dump on an auto generated schema, all of the related fields will be dump only with its primary key? Is there a way to work around this. That would be very helpful. Thanks in advance

**Comment by sloria** [comment]
@mato2000 you can declare explicit `Nested` fields for your relationships. see `BookSchemaWithNested` above

**Comment by mato2000** [comment]
Thanks for the reply! I was trying this example but it was slightly different and didn't work. Fixed and now works. Thanks and sorry for bothering!

**Comment by rchukkayapally** [comment]
[mato2000](https://github.com/mato2000)
How did you solve this problem?

**Comment by zedrdave** [comment]
@sloria I know this is an old issue, but TBH, this seems like a major limitation of `SQLAlchemyAutoSchema`: practically any DB schema will have a lot of nested relationship, and this forces a lot of boilerplate where this could easily be inferred from the SQLA models.

You mention this being by design to keep things flexible, can you develop your thoughts on that? At worst, this sounds like it could be provided as an optional feature, the same way `include_relationships` is…

**Comment by oelhammouchi** [comment]
Has there been any news on this? I'm loving the library so far, but I'm also running up against this limitation of `SQLAlchemyAutoSchema`. It would be very nice if it were an option to autogenerate `Nested` fields.
