### ISSUE TITLE
Ordering output doesn't work for auto_field

### ISSUE THREAD

**Issue by KwonL** [marshmallow-code/marshmallow-sqlalchemy#306]
In marshmallow, to order serialization output, set ordered = True in the Meta class as follows.

```python
class MyModelSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = MyModel
        ordered = True

    some_field = auto_field(validate=validate.Range(min=0, max=10))
```

It works well without ```auto_field```, but it generate following error with ```auto_field```.

```
AttributeError: 'SQLAlchemyAutoField' object has no attribute '_creation_index'
```

Is there any solution for this?

**Comment by peterschutt** [comment]
I think I have worked out a fix, but I'm not a maintainer so would have to wait until someone is able to pay the issue some attention.

Say with this model:

```py
class MyModel(Base):
    __tablename__ = "mymodel"
    id = Column(Integer, primary_key=True, autoincrement=True)
    some_field = Column(Integer, nullable=False)
```
and this schema (no `auto_field()`):
```py
class MyModelSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = MyModel
        ordered = True
```
... an instance serialized to: `OrderedDict([('id', 1), ('some_field', 111)])`.

And with this schema (with `auto_field()`):

```py
class MyModelSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = MyModel
        ordered = True

    some_field = auto_field()
```
... the same instance serialized to: `OrderedDict([('some_field', 111), ('id', 1)])`.

Is it confusing, expected, or doesn't matter that the declared field is ordered before the auto generated field?

**Comment by KwonL** [comment]
> Is it confusing, expected, or doesn't matter that the declared field is ordered before the auto generated field?

If we can get consistent result, I think order of field doesn't matter.
It makes sense that auto_field  is ordered before generated field because we explicitly declared that field.

**Comment by sloria** [comment]
Release in 0.23.0
