### ISSUE TITLE
sqla_session is defined twice in the ModelSchemaOpts docs

### ISSUE THREAD

**Issue by WhyNotHugo** [marshmallow-code/marshmallow-sqlalchemy#323]
`sqla_session` appears twice [here](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/api_reference.html#marshmallow_sqlalchemy.ModelSchemaOpts):

![2020-06-15T18:16:56,852204453+02:00](https://user-images.githubusercontent.com/730811/84681475-b1355500-af23-11ea-9059-8d25e8b0edf5.png)

**Comment by 3j14** [comment]
This is due to the documentation in this file:

https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/5a43cbb7dc556580da58ce0070e635bfef252840/src/marshmallow_sqlalchemy/schema/model_schema.py#L18

Fixing this is just a matter of removing the corresponding line ;)

**Comment by WhyNotHugo** [comment]
Thanks!
