### ISSUE TITLE
Questions about load_instance with multiple fields

### ISSUE THREAD

**Issue by 3j14** [marshmallow-code/marshmallow-sqlalchemy#324]
I have a question about the inner workings of `SQLAlchemySchema`'s `load_instance` option that I could not find in the documentation.

I have a simple model like this:

```python
class Document(Model):
    id = db.Column(db.Integer, primary_key=True, unique=True, nullable=False)
    name = db.Column(db.String(255), unique=False, nullable=False)
```

with its schema

```python
class DocumentSchema(SQLAlchemySchema):
    class Meta:
        model = Document
        load_instance = True

    id = auto_field()
    name = auto_field()
```

Let's assume that I have a single document with `id=1` and `name='Foo'`. When I now load its instance using 

```python
instance = schema.load({'id': 1, 'name': 'Foo'}, session=session)
```

I get the actual instance. When I now change the `name`:

```python
instance2 = schema.load({'id': 1, 'name': 'Bar'}, session=session)

instance is instance2  # True
```

I still get the same instance. This is actually desirable, as I use this in an API e.g. for changing the name of a document by sending some JSON with the document `id` and the updated `name`. However, I was curious why this works when one field does not match the instance. Am I only getting an instance when the `primary_key` is present or any other unique field?

I would be happy to document this behaviour as I feel the documentation for `load_instance` is a bit lacklustre. If someone could provide me with the implementation and its details, I'd be happy to get to work.

**Comment by Kimserey** [comment]
> However, I was curious why this works when one field does not match the instance. Am I only getting an instance when the primary_key is present or any other unique field?

The docstring in `LoadInstanceMixin` specifies the behaviour: _Update an existing row_.

https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/37ded650384756904d8af7af63cbc29c0b5280b7/src/marshmallow_sqlalchemy/schema/load_instance_mixin.py#L58-L65
