### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by romabysen** [marshmallow-code/marshmallow-sqlalchemy#35]
After upgrading to 0.6.0 I get an "Invalid Syntax" exception on line 133 in schema.py:

``` python
filters = {
    column.key: data.get(column.key)
    for column in columns
}
```

"for column in columns" is not a valid syntax.

**Comment by sloria** [comment]
What version of Python are you using?

**Comment by romabysen** [comment]
I get it on 2.6 but not on 2.7 and up.

**Comment by sloria** [comment]
This package currently only supports 2.7 and up.

**Comment by romabysen** [comment]
Ah, that explains it. Perhaps it should not be possible to install 0.6.9 from pypi on 2.6 though.

**Comment by sloria** [comment]
AFAIK, there isn't a way in setuptools to prevent installing a package on an incompatible version, even though package metadata may include the supported version in its classifiers: https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/setup.py#L55-L61

**Comment by sloria** [comment]
Closing for now.
