### ISSUE TITLE
Pypi page mistakenly states requirements for 0.24.0 version

### ISSUE THREAD

**Issue by potiuk** [marshmallow-code/marshmallow-sqlalchemy#352]
The https://pypi.org/project/marshmallow-sqlalchemy/ states that:

```
Requires Python >= 3.6, marshmallow >= 2.15.2, and SQLAlchemy >= 1.2.0.
```

Where in the setup.py there is 

```
INSTALL_REQUIRES = ("marshmallow>=3.0.0", "SQLAlchemy>=1.2.0")
```

So clearly one of those is wrong.

**Comment by sloria** [comment]
Good catch. The docs have been fixed. marshmallow-sqlalchemy only supports marshmallow>=3.0.0 because marshmallow 2 is EOL.

**Comment by potiuk** [comment]
Cool. Thanks!
