### ISSUE TITLE
ModelSchema default behaviour needs a lot of overriding

### ISSUE THREAD

**Issue by paj28** [marshmallow-code/marshmallow-sqlalchemy#36]
The current behaviour of ModelSchema is not that useful to me. Where I have, say, an "order" many-to-one relationship, by default it dumps a field "order" with the order_id, and this serialised data does not then load. It would be more helpful to dump this as field "order_id". one-to-many relationships are similarly not that useful. 

Right now I am using a lot of excludes and manually defined fields, but this is unnecessary. In fact, marshmallow-sqlalchemy already has much more helpful default logic, on TableSchema, especially with include_fk=True. I can't directly use TableSchema as it only supports dump and I also need to load.

However, a one line change to schema.py really helps:

```
return converter.fields_for_model(opts.model, fields=opts.fields, exclude=opts.exclude)
-->
return converter.fields_for_table(opts.model.__table__, include_fk=True, fields=opts.fields, exclude=opts.exclude)
```

I realise this would break compatibility, but it seems a much more helpful default to me.

**Comment by paj28** [comment]
I've now realised I can do this quite easily with a custom converter:

```
class MyModelConverter(marshmallow_sqlalchemy.convert.ModelConverter):
    def fields_for_model(self, model, include_fk=True, fields=None, exclude=None):
        return self.fields_for_table(model.__table__, include_fk, fields, exclude)
```

**Comment by sloria** [comment]
@jmcarp Has just added the include_fk as a class Meta option.
