### ISSUE TITLE
Define a marshamllow List field using marshmallow_sqlalchemy

### ISSUE THREAD

**Issue by damartcode** [marshmallow-code/marshmallow-sqlalchemy#367]
I'm trying to create a Schema using marshmallow_sqlalchemy. I want to create a list out of two entries of the Database, x_coordinate and y_coordinate, however, I'm not sure how to do that.

Here's the Schema
```python
from marshmallow_sqlalchemy import SQLAlchemySchema, auto_field
class LocationSQLAlchemySchema(SQLAlchemySchema):
    class Meta:
        model = Location
        load_instance = True
    
    location_id = auto_field('id')
    name = auto_field('name')
    user_uid = auto_field('customer_id')
    maps_url = auto_field('maps_url')
    coordinates = fields.List(Meta.model.x_coordinate,Meta.model.y_coordinate) #This is what I don't know how to define.
```
Here's the Model I'm using for this Schema:
```python
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.dialects.mysql import INTEGER
db = SQLAlchemy()
class Location(db.Model):
    __tablename__ = 'cleaning_locations'
    id = db.Column(db.String(128), primary_key=True, unique = True)
    name =  db.Column(db.String(45), nullable = False)
    customer_id = db.Column(db.String(45),nullable = False)
    maps_url = db.Column(db.String(2048),nullable = False)
    x_coordinate = db.Column(db.Numeric(precision = 8, scale=5), nullable = False)
    y_coordinate = db.Column(db.Numeric(precision = 8, scale=5), nullable = False)
    address = db.Column(db.String(255))
    country = db.Column(db.String(45))
    state = db.Column(db.String(45))
    size = db.Column(INTEGER(unsigned=True), nullable = False )
    rooms = db.Column(INTEGER(unsigned=True), nullable = False )
    bathrooms = db.Column(INTEGER(unsigned=True), nullable = False )
    kitchens = db.Column(INTEGER(unsigned=True), nullable = False )
```
How can I make the Schema to represent the coordinates as a list containing the x_coordinate and the y_coordinate?

**Comment by Unix-Code** [comment]
Marshmallow is primarily for serialization/deserialization of defined fields. What you're asking for seems to be a way to define a new field. In your case, that's probably way easier done by adding a `coordinates` `column_property`/`hybrid_property` ([SQLAlchemy feature](https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html#using-a-hybrid)) to your Location model (which should be equivalent to `(Location.x , Location.y)`). If you want to optimize it and save the computed column, you can use some more advanced ORM/DB features (ie TriggeredColumn, etc).

Once this new field/property exists, you can make use of `auto_field` like usual.

**Comment by damartcode** [comment]
This gives me a lot of perspective. I'm super new on everything used here but Python, never worked on backend, dbs or anything like that and trying to learn as I go, but I believe the model itself need some improvement, and the db design as well. 

Thanks for the help!
