### ISSUE TITLE
[Question] How to create optional fields

### ISSUE THREAD

**Issue by aprilahijriyan** [marshmallow-code/marshmallow-sqlalchemy#375]
Hi,

I'm looking for a way to create optional fields with marshmallows.

Here's the schema that I use.

```python

class UpdateUserSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password", "roles")

    password = fields.String(allow_none=True)
    roles = fields.List(fields.String(), allow_none=True)
```

Thank you in advance.

**Comment by sloria** [comment]
Your issue will be much easier to diagnose if you provide a minimal reproducible example.

My guess is that one of the autogenerated fields in your `SQLAlchemyAutoSchema` is required.

You can check by accession `fields`:

```python
UpdateUserSchema().fields["first_name"].required  # => True
```

To override `required`, use `auto_field`, as lafrech pointed out.
