### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object sqlalchemy for nested schema of whole table

### ISSUE THREAD

**Issue by AwaisBinKaleem** [marshmallow-code/marshmallow-sqlalchemy#395]
facing error 
maximum recursion depth exceeded while calling a Python object sqlalchemy for nested schema of whole table
so we have to increase stack size or **exclude** **argumentnt** the nested fields

**Comment by AbdealiLoKo** [comment]
It sounds like your sqlalchemy schema may have a recursive reference
We would need some example code to understand how to reproduce this

**Comment by AwaisBinKaleem** [comment]
when posted this issue, i was new to sqlalchemy, but now i understood the error.it was not a bug so it does not need to be posted on this page.it was just a simple error that is commonly available on internet.
so i am closing this issue.
