### ISSUE TITLE
Generate schemas for tables

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow-sqlalchemy#4]
I would like to be able to do something like this:

``` python
users = Table('users', metadata,
    Column('id', Integer, primary_key=True),
    Column('name', String),
    Column('fullname', String),
)

class UserSchema(TableSchema):
    class Meta:
        table = users
```

Because sometimes you want to use SQLAlchemy, but you don't want an ORM.

**Comment by dpwrussell** [comment]
I assume you would serialize the row? What about deserialization?

**Comment by jmcarp** [comment]
@dpwrussell yep, the idea is to serialize `RowProxy` objects. Just submitted a quick patch at #24--like I said there, not sure that there's a good approach for deserializing, so I left it out.
