### ISSUE TITLE
Custom TYPE_MAPPING

### ISSUE THREAD

**Issue by imhoffd** [marshmallow-code/marshmallow-sqlalchemy#42]
I am extending the `Schema` class from marshmallow for my schemas and extending the `TYPE_MAPPING` attribute, but because of [these lines here](https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/c6921777185bced18ccd6cf9114e645e90b057d2/marshmallow_sqlalchemy/convert.py#L141-L142), the `ModelConverter` doesn't pick up my changes, because it hardcodes marshmallow's `Schema` class.

``` python
from datetime import datetime
from marshmallow import Schema

[...]

class BaseSchema(Schema):

    TYPE_MAPPING = Schema.TYPE_MAPPING.copy()
    TYPE_MAPPING.update({
        datetime: APIDateTime,
    })

    def __init__(self, *args, **kwargs):
        if 'strict' not in kwargs:
            kwargs['strict'] = True
        super(BaseSchema, self).__init__(*args, **kwargs)
```

How do I override the mapping in marshmallow-sqlalchemy for datetime => my own custom field?

**Comment by fuhrysteve** [comment]
@dwieeb You're pretty close. I think you're looking for something like this:

``` python
from marshmallow_sqlalchemy import ModelSchema, ModelConverter
from sqlalchemy_utils.types import TimezoneType
from marshmallow import fields

class SQLAlchemyUtilsConverter(ModelConverter):
    SQLA_TYPE_MAPPING = dict(
        list(ModelConverter.SQLA_TYPE_MAPPING.items()) +
        [(TimezoneType, fields.Str)]
    )

class MyModelSchema(ModelSchema):
    class Meta:
        model_converter = SQLAlchemyUtilsConverter
```

only in your case, something more like:

``` python
class MyConverter(ModelConverter):
    SQLA_TYPE_MAPPING = dict(
        list(ModelConverter.SQLA_TYPE_MAPPING.items()) +
        [(datetime, APIDateTime)]
    )
```

**Comment by imhoffd** [comment]
Yeah, I know I can override `ModelConverter`, I just don't want to. Code bases can easily use thousands of schemas. I shouldn't have to specify `model_converter =` for each one when I have a BaseSchema with a `TYPE_MAPPING` that should be picked up.

I think marshmallow-sqlalchemy needs a patch such that `_get_field_class_for_data_type()` is called with a reference to `model` from `fields_for_model()` so that it can use the `TYPE_MAPPING` from the user's schema classes OR fall back to `marshmallow.Schema`'s `TYPE_MAPPING`.

**Comment by fuhrysteve** [comment]
Hmm, not sure if I am misunderstanding your issue or not, but you could also do something like this if you wanted something resembling a custom `TYPE_MAPPING` in your `BaseSchema`:

``` python
class BaseSchema(ModelSchema):
    class Meta:
        model_converter = MyDefaultConverter
        # other defaults

class MyModelSchema(BaseSchema):
    class Meta(BaseSchema.Meta):
        # MyModelSchema specific customizations
        pass
```

The only downside is that you need to remember to have your `Meta` classes extend `BaseSchema.Meta` if you want to customize it further.

**Comment by imhoffd** [comment]
Yeah, that'd be fine for my use case.

I _still_ think the built-in ModelConverter should respect the schema class's type mapping, and not be hardcoded to use the marshmallow schema's type mapping--that's not how inheritance should work. :confused:  

Perhaps I will do a PR to see how the change is received.

**Comment by fuhrysteve** [comment]
Yeah, I'm not sure if that's intentional or not. PR would be a great way to find out haha

**Comment by sloria** [comment]
#49 should address this issue. ModelSchema will now respect a Schema subclass's `TYPE_MAPPING`.

**Comment by imhoffd** [comment]
Awesome, @sloria! Thank you.
