### ISSUE TITLE
Expose Model @property

### ISSUE THREAD

**Issue by petertrotman** [marshmallow-code/marshmallow-sqlalchemy#43]
I can't work out how to expose model properties created using @property. E.g. as from your examples:

```
@property
def url(self):
    return url_for('author', id=self.id)
```

I might want to include this property when returning data. However, the best help I could find from the API reference is using property2field, but in trying to use:

```
url = property2field(Author.__mapper__.get_property('url')
```

I get the following error:

```
sqlalchemy.exc.InvalidRequestError: Mapper 'Mapper|Post|posts' has no property 'url'
```

It seems like this ought to be possible, but I can't work it out. Any help appreciated.

**Comment by sloria** [comment]
`property2field` is used for SQLAlchemy properties, which are different from Python properties. To serialize Python property, just add a declared field on your schema. 

``` python
url = fields.Str()
```
