### ISSUE TITLE
implement __envelope__

### ISSUE THREAD

**Issue by alex-frx** [marshmallow-code/marshmallow-sqlalchemy#441]
`__envelope__ `is missing or it is unknow how to get it to work 
[See envelope](https://marshmallow.readthedocs.io/en/stable/extending.html?highlight=envelope#example-enveloping)

**Comment by sloria** [comment]
The `__envelope__` isn't an out-of-box feature of marshmallow nor marshmallow-sqlalchemy. That documentation is just of example of how you can use pre/post hooks to implement enveloping.
