### ISSUE TITLE
Fails when using SQLAlchemy @hybrid_property instead of normal @property

### ISSUE THREAD

**Issue by jeffwidman** [marshmallow-code/marshmallow-sqlalchemy#46]
I'm using Flask-SQLalchemy, Flask-Marshmallow, Marshmallow-SQLAlchemy and Marshmallow. 

A couple of my SQLAlchemy models have [`@hybrid_properties`](http://docs.sqlalchemy.org/en/latest/orm/mapped_sql_expr.html#using-a-hybrid).

Here's my field:

```
count_direct_child_items = field_for(GearCategory, 'count_direct_child_items', dump_only=True)
```

When it tries to fetch the hybrid property, it fails because the hybrid property is not in the mapper. 

[`all_orm_descriptors`](http://docs.sqlalchemy.org/en/latest/orm/mapping_api.html#sqlalchemy.orm.mapper.Mapper.all_orm_descriptors) may be useful for fixing this, as mentioned in this SQLAlchemy [mailing list issue](https://groups.google.com/forum/#!topic/sqlalchemy/aDi_M4iH7d0).

Here's the actual traceback:

```
Traceback (most recent call last):
  File "/Users/jeffwidman/.virtualenvs/api_rc_flask/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 1804, in get_property
    return self._props[key]
KeyError: 'count_recursive_child_items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    from app.serializers.gear_serializers import (GearCategorySchema, GearItemSchema,
  File "/Users/jeffwidman/Code/rc/api_rc_flask/app/serializers/gear_serializers.py", line 9, in <module>
    class GearCategorySchema(marshmallow.ModelSchema): # TODO switch to HyperlinkModelSchema
  File "/Users/jeffwidman/Code/rc/api_rc_flask/app/serializers/gear_serializers.py", line 25, in GearCategorySchema
    count_recursive_child_items = field_for(GearCategory, 'count_recursive_child_items', dump_only=True)
  File "/Users/jeffwidman/.virtualenvs/api_rc_flask/lib/python3.5/site-packages/marshmallow_sqlalchemy/convert.py", line 117, in field_for
    prop = model.__mapper__.get_property(property_name)
  File "/Users/jeffwidman/.virtualenvs/api_rc_flask/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 1807, in get_property
    "Mapper '%s' has no property '%s'" % (self, key))
sqlalchemy.exc.InvalidRequestError: Mapper 'Mapper|GearCategory|gear_category' has no property 'count_recursive_child_items'
```

**Comment by jmcarp** [comment]
What would you expect `field_for` to return, given the name of a hybrid property? As far as I can tell, it doesn't seem like we can introspect much of anything about a hybrid property other than its name--we don't know its type, its precision, whether it's a list, etc. This might be a case where it's simpler for the user to define the field manually: plain old `fields.Str(dump_only=True)`.

**Comment by jeffwidman** [comment]
Well, I don't understand the internals of how Marshmallow-SQLAlchemy grabs the type. I just assumed it'd look at the result generated by the `@hybrid_property`, check it's baseclass and if possible convert to either int or string. 

Makes sense that it doesn't do that, and I'm totally fine defining a field manually. 

Also, what do you think about a PR adding a note on this scenario to the docs? Possibly a 'FAQ' page that covers some of the common scenarios that are sure to pop up. Although I guess googling is fine too now that this issue exists to document how to handle.

**Comment by saksham219** [comment]
Hey I am using flask-sqlalchemy and all my models are built using it. I want to use @hybrid_property in one of my models. How should I import it? Does flask-sqlalchemy have hybrid package like sqlalchemy?

**Comment by lafrech** [comment]
> This might be a case where it's simpler for the user to define the field manually: plain old fields.Str(dump_only=True).

Note you also need to exclude explicitly the field targeted by the property.

```py
import sqlalchemy as sqla
from sqlalchemy.ext.hybrid import hybrid_property
import marshmallow as ma
import marshmallow_sqlalchemy as msa


class User(Base):
    __tablename__ = "users"

    id = sqla.Column(
        sqla.Integer,
        primary_key=True
    )
    name = sqla.Column(
        sqla.String(80),
        unique=True,
        nullable=False
    )
    _is_admin = sqla.Column(
        sqla.Boolean(),
        nullable=False
    )

    @hybrid_property
    def is_admin(self):
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        auth.authorize(self.current_user(), "set_admin", self)
        self._is_admin = is_admin


class UserSchema(AutoSchema):
    class Meta:
        table = User.__table__
        exclude = ( "_is_admin", )  # <-- exclude original field

    id = msa.auto_field(dump_only=True)
    is_admin = ma.fields.Boolean(dump_only=True)  # <-- declare property
```
