### ISSUE TITLE
schema.load is no longer taking into consideration the Models default values

### ISSUE THREAD

**Issue by AdrielVelazquez** [marshmallow-code/marshmallow-sqlalchemy#47]
As of today 12/9 loading a dictionary to a model that has default fields is no longer using the alchemy default fields and throwing errors. 

Example below, Python 3

``` python
from datetime import datetime

from app import db
from app.models.base import Base as SQLBASE
from app.schemas import Base

__all__ = ["TestModel"]

class TestModel(SQLBASE):
    __tablename__ = 'test_table'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(255), nullable=False, unique=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

class TestModelSchema(Base):

    class Meta(Base.Meta):
        dateformat = "%Y-%m-%d"
        model = TestModel

test_schema = TestModelSchema()

class TestSchemaFunctions:

    def test_no_defaults(self):
        dict_model = {"name": "TestName"}
        results = test_schema.load(dict_model)
        print(results.errors, results.data)
        # (Pdb) results.errors
        # {'updated_at': ['Missing data for required field.'], 'created_at': ['Missing data for required field.'], 'id': ['Missing data for required field.']}
        # (Pdb) results.data
        # {'name': 'TestName'}
```

**Comment by AdrielVelazquez** [comment]
I should note that passing the partial flag now allows it to work. 

Is that new?

``` python
from datetime import datetime

from app import db
from app.models.base import Base as SQLBASE
from app.schemas import Base

__all__ = ["TestModel"]

class TestModel(SQLBASE):
    __tablename__ = 'test_table'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(255), nullable=False, unique=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

class TestModelSchema(Base):

    '''
    Serializer for Advertiser

    .. seealso: Advertiser Model for all acceptable params
    '''
    class Meta(Base.Meta):
        dateformat = "%Y-%m-%d"
        model = TestModel

test_schema = TestModelSchema()

class TestSchemaFunctions:

    def test_no_defaults(self):
        dict_model = {"name": "TestName"}
        results = test_schema.load(dict_model, partial=True)
        print(results.errors, results.data)
```

**Comment by jmcarp** [comment]
As of release 0.7, columns that aren't `nullable` are translated to fields that are `required`. One solution to this issue would be to relax that constraint for columns with `default` values. Alternatively, we could also try to use the default value on deserialization, but `default` values in SQLAlchemy are allowed to access the context of the current row and to call SQL functions, both of which would be hard to introspect.

What do you all think @AdrielVelazquez @sloria?

**Comment by AdrielVelazquez** [comment]
@jmcarp I understand the reasoning; and we were able to switch the models that have defaults to not have nullable=False. 

However, there's another bug. If you have a model with the a column that's primary_key and auto_increment=True. Marshmallow still throws an error when not receiving an id. 

This is definitely a bug that anything considered a primary key with auto_increment=True should not be defaulted to required cause an id will never be passed. 

Thoughts?

**Comment by jmcarp** [comment]
So it seems like there are several cases in which a non-nullable column shouldn't be required: if it has a `default` value, or `server_default`, or `autoincrement`. How about changing our logic so that non-nullable columns are required, unless any of the above attributes is set?

**Comment by AdrielVelazquez** [comment]
Sounds good.

**Comment by jmcarp** [comment]
I took a stab at this in #48. Feedback welcome @AdrielVelazquez @sloria
