### ISSUE TITLE
SQLAlchemy 2.0 support

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/marshmallow-sqlalchemy#488]
marshmallow-sqlalchemy does not support sqlalchemy 2.0+.

This is what I think we should do:

- Fix CI. In #486, I propose a complete CI update and a move from Azure to GHA.
- Lock sqlalchemy < 2.0. I did this in #486 to let CI pass.
- Release 0.28.2 with sqlalchemy < 2.0 support

Then in a second step

- Drop salalchemy 1.3
- Fix sqlalchemy 2.0 compat warnings that were added in 1.4 (work begun in https://github.com/marshmallow-code/marshmallow-sqlalchemy/tree/sqla_1.4)
- Provide sqlalchemy 2.0 support
- Release 0.29 with sqlalchemy 1.4+ support

(We may still accept bugfixes in 0.28.x branch for a while.)

-------------------------------------------------------------------------------------

What I need:

- Agreement. I'm not lead maintainer here. Is this plan fine?
- Removal of Azure hook and API_KEY to allow releases from GHA
- Permissions to push to master: last time I tried to release I had issues (#461) that we never solved and the release never happened

@sloria do you think you could give me ownership of this repo or at least the same privileges as marshmallow, and either share PyPI ownership or provide API_KEY?

I didn't really mean to maintain this. I'm not familiar with the code base. But we use it and will need 2.0 support, and no one stepped in to take over, so I can try to do my best with maintenance chores.

**Comment by sloria** [comment]
@lafrech +💯 on this plan. i've given you owner access in both GH and pypi. let me know if you're still missing privs

**Comment by lafrech** [comment]
Thanks. Now I need to carve out time to follow [the plan](https://www.youtube.com/watch?v=QiIA0QgxMxc).

**Comment by lafrech** [comment]
0.28.2 released. For some reason the automatic release failed so I released manually. I'll investigate this another day, it's late.

SQLA 1.3 support dropped in dev branch.

(**Edit**: I didn't find it yesterday. Here's the SQLA page saying 1.3 is EOL: https://www.sqlalchemy.org/download.html#status-desc-eol.)

**Comment by rimvislt** [comment]
So now we locked into 2 dependencies until it is solved:
**SQLAlchemy==2.0.1
marshmallow-sqlalchemy==0.28.1**

Majority of marshmallow works with 2.0.1 version but does not work with anything above it. Since we start changing our code to support 2.0.1 we can not upgrade marshmallow, since dependency lock was much later introduced than SQLAlchemy.

**Comment by rimvislt** [comment]
@lafrech URL which you mentioned above does not seem to be working 
`work begun in https://github.com/marshmallow-code/marshmallow-sqlalchemy/tree/sqla_1.4`

Let me know if we have branch or some base for SQLAlchemy 2.0 support.
I can contribute a bit during weekends.

**Comment by lafrech** [comment]
Thanks @rimvisit for the help.

The branch I mentioned above was merged already. I believe I solved all 2.0 compat warnings.

Migration steps here: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html.

We should be pretty close to the "test against SQLAlchemy 2.0" step.

**Comment by lafrech** [comment]
SQLAlchemy 2.0 support merged in #495.

Shipping soon. Time to test on your code bases to spot issues that would have been uncaught.

**Comment by rimvislt** [comment]
Thank you I will try to get it tested.

**Comment by lafrech** [comment]
Allright, I decided I had enough feedback already.

SQLAlchemy 2.0 support is achieved in marshmallow-sqlalchemy 0.29.0, available today at your favorite store.

**Comment by jdimmerman** [comment]
Thank you @lafrech!
