### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by braginkit** [marshmallow-code/marshmallow-sqlalchemy#497]
According to [docs](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/), requirements for marshmallow-sqlalchemy are:
"Requires Python >= 3.7, marshmallow >= 3.0.0, and SQLAlchemy >= 1.3.0"

I'm using:
- python 3.11
- marshmallow==3.2.2
- SQLAlchemy==1.3.6

When I try to pip install marshmallow-sqlalchemy==0.29.0, this happens:

```
ERROR: Cannot install -r requirements/base (line 13) and SQLAlchemy==1.3.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested SQLAlchemy==1.3.6
    marshmallow-sqlalchemy 0.29.0 depends on SQLAlchemy<3.0 and >=1.4.40
```

As you can see, docs and pip are not on the same page.

**Comment by lafrech** [comment]
I just fixed the docs and README. 1.4.40 required indeed.

Migrating from 1.3 to 1.4 shouldn't be an issue.
