### ISSUE TITLE
Generate schemas for abstract models

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow-sqlalchemy#5]
This is admittedly a very narrow use case, but users may occasionally want to create schemas for abstract models. Since by definition abstract models don't have mappers, the logic used to list columns and relationships won't work. This could be handled easily enough by listing model attributes without using the mapper, although it would be less elegant:

``` python
for key in dir(model):
    attr = getattr(model, key)
    if isinstance(attr, (Column, MapperProperty)):
        # ingest column
        ...
```

The main plausible use case is a user who wants to define an ABC with several concrete subclasses, but only wants to serialize columns defined on the ABC. @sloria is this too narrow to support?

**Comment by sloria** [comment]
Seems to be a valid use case, and if the implementation doesn't add significant complexity (which it seems not to), I would be open to this.

**Comment by dfee** [comment]
I think I just ran into this. Major bummer.

**Comment by sloria** [comment]
Closing this for now, as the use case is supported by using column2field. 

```python
class ArtistBase:
    name = column2field(models.ArtistBase.name)

class ArtistSchema(ArtistBase, ModelSchema):
    class Meta:
        model = models.Artist
```

It's verbose, but it works. Things will get much more concise if we go with https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/240#issuecomment-527919980
