### ISSUE TITLE
Expand docs clarifying the benefits of using `field_for()` rather than typical `fields.Str()`

### ISSUE THREAD

**Issue by jeffwidman** [marshmallow-code/marshmallow-sqlalchemy#51]
I'm still trying to understand the benefits of using marshmallow-sqlalchemy above what marshmallow already gives me. 

The obvious one is auto-generation of fields, but for my schemas, most of the fields require additional arguments such as `dump_only` or `required`, so this doesn't add much for me. 

I checked the docs, but couldn't find much. However, I was just reading the code and noticed that a length validator is automatically included when sqlalchemy has a length constraint on the underlying db column. Similarly, https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/47#issuecomment-164083869 mentions that fields that aren't allowed to be null have marshmallow `required` added. 

Both are clever optimizations--and I think it'd be worth mentioning in the docs. 

Ultimately, be nice if there was a clear set of 'here's the benefits of this extension over and above vanilla marshmallow' as well as 'here's what using `field_for(column)` provides over and above the typical `fields.str()` or `fields.Integer()`'

**Comment by shuttle1987** [comment]
I'd also like to see some documentation or examples of this.

**Comment by sloria** [comment]
Closing this, as `field_for` is no longer recommended in the docs. `auto_field` provides a much improved API, and the benefits should be clearer (see #240 ). If not, feel free to send a docs PR =)
