### ISSUE TITLE
Example of serializing a SQLAlchemy query result consisting of several Model objects

### ISSUE THREAD

**Issue by EdCampion** [marshmallow-code/marshmallow-sqlalchemy#56]
Hi,
First off, apologies if this is documented and I've missed it. Could an example be provided of how to serialize a SQLAlchemy query result, where join has been used to return multiple Model objects?

**Comment by whoiswes** [comment]
Not sure if this helps, but I whipped up a simple gist based off Miguel Grinbergs Flask MegaTutorial microblog, and adapted it to Marshmallow-Sqlalchemy.  I'm relatively new to Python so this may not be the optimal way of doing things, but this works and demonstrates how MA-SQLA can automatically parse related schemas.  I wanted to do something fairly simple, but I'm using these same with much larger and more complex models and it works wonderfully.

https://gist.github.com/whoiswes/64afe531a025c9b0b333

Again, hope this is useful!

**Comment by raminfp** [comment]
@whoiswes Yes, but not work it marshmallow on self relationship example code 

``` python

class self_reflation(Base):

        __tablename__ = 'tbSelf'

        id = Column(Integer, primary_key=True)
        name = Column(String(50))
        parent_id = Column(Integer, ForeignKey('tbSelf.id'))
        children = relationship(lambda: self_reflation, remote_side=[id])
```

**Comment by whoiswes** [comment]
I've never seen that type of relationship config, but this works (currently using a derivation of it):

```
Parent_Child = Table('Parent_Child', Base.metadata,
    Column('parent_id', Integer, ForeignKey('foobar.id')),
    Column('child_id', Integer, ForeignKey('foobar.id'))
    )

class foobar(Base):
    __tablename__ = 'foobar'
    id = Column(Integer, primary_key=True)
    data = Column(String(80), nullable=False)
    children = relationship('Posts', secondary='Parent_Child', primaryjoin=(id == Parent_Child.c.parent_id), secondaryjoin=(id == Parent_Child.c.child_id), backref='parents', lazy='joined')

class foobarSchema(ModelSchema):
    children = fields.Nested('self', many=True, exclude=('children',))
    class Meta:
        model = foobar
        sqla_session = session
```

**Comment by raminfp** [comment]
do you test with self relationship sqlalchemy and serializing marshmallow to python type?

**Comment by whoiswes** [comment]
Yes, the code above can serialize or deserialize the parent/child relationships.  Like I said, I'm using that code for self-referential many-to-many relationships.

**Comment by raminfp** [comment]
Can you test this model?

``` python
class self_reflation(Base):

        __tablename__ = 'tbSelf'

        id = Column(Integer, primary_key=True)
        name = Column(String(50))
        parent_id = Column(Integer, ForeignKey('tbSelf.id'))
        children = relationship(lambda: self_reflation, remote_side=[id]
```

**Comment by fuhrysteve** [comment]
I'm not 100% sure we are trying to solve the same problem, but I've been working on figuring out a good way to handle the case where I occasionally want to add a "column" to a result. Let's pretend we're building a web store, and I want to optionally have my `/api/users` endpoint return, along with a list of users, the total number of orders they've made in the past.

``` python
class UserSchema(ModelSchema):
    id = fields.Integer()
    name = fields.String()
    class Meta:
        sqla_session = db.session
        model = User

users = db.session.query(
    User,
    func.count(User.orders).label('total_orders')
).all()

>>> print(users)
[(<User id=1>, 24), (User id=2, 10), (User id=2, 10)]
```

Gah! I can't just pass this strange data structure into UserSchema.. And I'm hesitant to customize UserSchema for this one weird case... so:

``` python
from marshmallow import Schema, post_dump

class UserWithTotalOrdersSchema(Schema):
    total_orders = fields.Integer()
    User = fields.Nested(UserSchema)

    @post_dump
    def unnest(self, data):
        for key, val in data.items():
            if key != 'User':
                data['User'][key] = val
            return data['User']

schema = UserWithTotalOrdersSchema()
users_serialized = schema.dump(phs, many=True).data
```

There, now from the client's perspective, it's as though `total_orders` is an attribute of `User`.

**Comment by saksham219** [comment]
@fuhrysteve  could you tell me what phs is in the line users_serialized = schema.dump(phs, many=True).data  ?

**Comment by fuhrysteve** [comment]
@saksham219  `phs` in that case was a sqlalchemy query result object
