### ISSUE TITLE
How to load all fields into schema from model which loads fields from database directly?

### ISSUE THREAD

**Issue by fegamon** [marshmallow-code/marshmallow-sqlalchemy#569]
I have this shema:

```python
class Users(SQLAlchemyAutoSchema):
    class Meta:
        model = models.Users
        include_fk = True
        include_relationships = True
```

The model is:

```python
class Users(db.Model):
    __table__ = db.Model.metadata.tables['dbo.Users']
```

As you can see, the columns in the model are directly mapped from db table, and if I print columns from model, all columns are loaded, but if i print the schema, It is just an empty dict. I don't know how to load all fields without set them manually.

**Comment by sloria** [comment]
looks like you have 

```python
    class Meta:
        model: models.Users
```

rather than

```python
    class Meta:
        model = models.Users
```

can you try changing that?

**Comment by fegamon** [comment]
The solution was set fields from model's columns:

```python
class Users(SQLAlchemyAutoSchema):
    class Meta:
        model: models.Users
        include_fk = True
        fields = models.Users.__table__.columns.keys() # This is the solution
```

I'll keep this issue for people who are facing the same problem.
