### ISSUE TITLE
Access to relationship model

### ISSUE THREAD

**Issue by raminfp** [marshmallow-code/marshmallow-sqlalchemy#59]
Hi,

``` python

author = Author(name='Chuck Paluhniuk')
book = Book(title='Fight Club', author=author)
session.add(author)
session.add(book)
session.commit()

author_schema.dump(author).data
```

output model book:

```
# {'books': [123], 'id': 321, 'name': 'Chuck Paluhniuk'}
```

how to access to model books if i set list model like ,

```
lst = ses.query(author ).all()
author_schema.dump(lst).data
```

output : 

```
# {'books': [123], 'id': 321, 'name': 'Chuck Paluhniuk'}
```

but i need access to model book?

**Comment by whoiswes** [comment]
Change

`author_schema.dump(lst).data`

to 

`author_schema.dump(lst, many=True).data`

???

**Comment by raminfp** [comment]
@whoiswes i get error with `data,error = UserSerializer.dump(jsonusers,many=True).data`  i think not work with self-reletionship :(

**Comment by whoiswes** [comment]
Disclaimer - I'm only a few months into Python so I might be missing stuff.

OK, I'm not following your code then.  Your query is referencing a Car model, but you're still dumping from author_schema - is that referencing your Car model?

I put together a gist for a simple relational model for another bug report, it might be useful (or not, again, I'm new at this) - see bug #56

**Comment by xarg** [comment]
@RaminFP Check the Author schema here: http://marshmallow-sqlalchemy.readthedocs.org/en/latest/recipes.html#overriding-generated-fields

Is this what you're looking for?

**Comment by raminfp** [comment]
@xarg Thanks , Work it,
