### ISSUE TITLE
`CONTRIBUTING.rst` is out of date

### ISSUE THREAD

**Issue by panda-byte** [marshmallow-code/marshmallow-sqlalchemy#610]
The [`CONTRIBUTING.rst`](https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/CONTRIBUTING.rst) seems to be out of date, as it references `X.Y-line` branches for bug fixes. However, only the `dev` branch exists.

**Comment by sloria** [comment]
good catch! updated
