### ISSUE TITLE
deserialize json model in model with marshmallow python

### ISSUE THREAD

**Issue by raminfp** [marshmallow-code/marshmallow-sqlalchemy#64]
I going to deserialize json model

Models:

``` python
class Users(Base):

        __tablename__ = 'users'

        ID = Column(Integer, primary_key=True,autoincrement=True)
        Username = Column(String(50),nullable=False,unique=True)
        Email = Column(String(200),nullable=False,unique=True)
        Name = Column(String(20))
        Password = Column(String(50))
        Date = Column(Date)

```

``` python
class Logs(UserBase):

        __tablename__ = 'logs'

        ID = Column(Integer, primary_key=True,autoincrement=True)
        UserLog = Column(String(50))
        log_id = Column(Integer, ForeignKey('users.ID'))
        log = relationship("Users",lazy="joined", backref=backref('logs'))

```

Schemas:

``` python
class LogsSchema(ModelSchema):
    class Meta:
        model = Logs
        sqla_session = Session

class UsersSchema(ModelSchema):
    logs = fields.Nested(LogsSchema,exclude=('log', ))
    class Meta:
        model = Users
        sqla_session = Session

```

json model request

``` python
<QueryDict: {u'Username': [u'ramin world'], u'logs': [u'[UserLog=test]'], u'Date': [u'null'], u'Password': [u'1234'], u'Email': [u'ramin@blacat.gmail.com'], u'Name': [u'Farajpour']}>
```

load json request:

``` python
{'Username': u'ramin world', 'Password': u'1234', 'Name': u'Farajpour', 'Email': u'ramin@blacat.gmail.com'}
```

you see model `u'logs': [u'[UserLog=test]']`is not on result.

**Comment by raminfp** [comment]
@sloria please answer?

**Comment by sloria** [comment]
Please do not ping me or others for attention on the same day that you post an issue. This project is done by volunteers in their limited free time; we will get to your issue when we find the time.

I'm a little unclear on your question. Are you seeing errors in the load result?

**Comment by raminfp** [comment]
Thanks.there is not error I have two model,when I use load with querydict django user model and log model but load convert json user model but log model in user model can not coverted , what's the problem?

**Comment by sloria** [comment]
There may not be an exception raised, but are there validation errors returned by `Schema.load`?

``` python
from pprint import pprint
result = UserSchema().load(..)
pprint(result.errors)
```

Since `logs` is a `Nested` field, it expects a dictionary as input. `['[UserLog=test]']` would be considered invalid input.
