### ISSUE TITLE
Incorrect SQLAlchemy dependency

### ISSUE THREAD

**Issue by alejom99** [marshmallow-code/marshmallow-sqlalchemy#65]
The convert.py file, at line 58 says:

`
postgresql.JSONB: fields.Raw
`

But postgresql.JSONB is not supported until SQLAlchemy 0.9.7. Yet, the setup.py lists SQLAlchemy>=0.7. So, any version between 0.7 and 0.9.6 is not really supported.

**Comment by sloria** [comment]
Good catch. I've updated the dependency in `setup.py`.
