### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Zitrax** [marshmallow-code/marshmallow-sqlalchemy#66]
http://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#base-schema-ii say that BaseOpts should use SchemaOpts, but with that I get:

AttributeError: 'BaseOpts' object has no attribute 'model_converter'

If I change it to ModelSchemaOpts it works though.

**Comment by sloria** [comment]
Good catch; I would certainly accept a pull request fixing the docs =)
