### ISSUE TITLE
Validating multi-table json

### ISSUE THREAD

**Issue by EdCampion** [marshmallow-code/marshmallow-sqlalchemy#71]
Is there anyway of using marshmallow-sqlalchemy to validate json which contains data for multiple tables?

Example:
Given 2 tables Question and InputQuestion where InputQuestion is an extension of Question,
the following json is posted

```
{  
    "question": {
        "question_type_id": 1,
        "client_date_created": "17:25:12.517000",
        "company_id": 74
         },
    "input_question": {
        "input_question_type_id": 1,
        "require_input_if_positive": false,
        "device_input_type_id": 1,
        "require_photo_if_positive": false
    }
}
```

My naive and unsuccessful attempt to validate this was to setup a schema, with nested instances of
ModelSchema classes.

``` python
class Linked_Checklist_Input_Question_Schema(Schema):
    question =  fields.Nested(Checklist_Question_Schema)
    input_question = fields.Nested(Checklist_Input_Question)

#test link schema
schema = Linked_Checklist_Input_Question_Schema()
#load example json
result = schema.load(data)
#which gives us as result.errors
{u'_schema': [u'Invalid type.']}
```

`

**Comment by EdCampion** [comment]
@sloria Appreciate this is not the done thing, but would be great if you could take a look at this.

**Comment by jmcarp** [comment]
@EdCampion: I took a look at this but couldn't replicate the issue you described. Could you post a more detailed code example? I'm wondering if `data` isn't a `dict` here--for example, if it's a `list`, the error you're describing would make sense.

**Comment by EdCampion** [comment]
@jmcarp Thanks for taking a look, was a very stupid error on my part. I was attempting to load the string representation of the dict instead of the dict. The error message makes complete sense, but when I didn't even know if this was possible I missed the point of it,

I do have one other question. I'm confused as to how marshmallow-sqlalchemy works when updating an entity. Is it possible to pass a subset of an entities fields and have marshmallow look up the full entity and check if the update vals will leave it in a legal state?
