### ISSUE TITLE
Checking unique constraints

### ISSUE THREAD

**Issue by Darkheir** [marshmallow-code/marshmallow-sqlalchemy#73]
Hi,

I have just a small question, is it actually possible to check unique constraint during validation ?

In my current application during the load of the json data everything is going well, and when I'm trying to persist the data I obtain an Integrity error since the unique filed value is already taken by another row.

ps: Thank you for this module that is really useful

**Comment by georgexsh** [comment]
@Darkheir before data flush to database, I don't see any method to detect uniqueness violation reliably, because another thread might change the data state in database.

**Comment by AbdealiLoKo** [comment]
Closing as the original question seems to be answered. Adding to database is the most reliable way to check for uniqueness due to multiple-thread/connections
