### ISSUE TITLE
Custom SQLAlchemy types with a python_type that is not a class fail on init

### ISSUE THREAD

**Issue by fuhrysteve** [marshmallow-code/marshmallow-sqlalchemy#84]
Let me start by saying this might not be a bug.

Looks like https://github.com/kelvinhammond/marshmallow-sqlalchemy/commit/12da838c8ca3e02516dd83852cef870d1d596b1b breaks compatibility with sqlalchemy-utils (particularly `PhoneNumberType`). It seems like a bug in sqlalchemy-utils where it has a `python_type` of `method` (rather than a class).

I have a pull request which should fix the issue:
kvesteri/sqlalchemy-utils#248

I think this is a bug in sqlalchemy-utils, but it might also be reasonable to be a little more forgiving by gracefully handling cases where `issubclass` will fail. Tough call - on the one hand it is good to be accommodating but on the other hand we should trust that people are adhering to what appears to be a pretty definitive interface definition:

http://docs.sqlalchemy.org/en/latest/core/type_api.html#sqlalchemy.types.TypeEngine.python_type

Here is the relevant stack trace:

``` python
  File "marshmallow_sqlalchemy/convert.py", line 219, in _add_column_kwargs
    if not python_type or not issubclass(python_type, uuid.UUID):
TypeError: issubclass() arg 1 must be a class

(Pdb) python_type
<bound method PhoneNumberType.python_type of PhoneNumberType(length=20)>
```

**Comment by sloria** [comment]
Thanks for reporting. I would much rather see this fixed in sqlalchemy-utils. As you mentioned, the interface for custom types dictates that `python_type` be implemented as a property. 

I would be open to merging your PR, but I'm going to hold off to see if your fix on sqlalchemy-utils gets merged.

**Comment by fuhrysteve** [comment]
Thanks @sloria, I tend to agree. I don't think my PR is necessarily a bad thing to do, but I agree it sets an unfortunate precedent.

**Comment by fuhrysteve** [comment]
https://github.com/kvesteri/sqlalchemy-utils/pull/248 was merged (with alterations) so this should no longer be an issue. Feel free to close or merge https://github.com/marshmallow-code/marshmallow-sqlalchemy/pull/85 as you see fit - I'm torn on it

**Comment by sloria** [comment]
Good to hear. I'm going to close that--for the reasons stated above. Thanks for addressing this!
