### ISSUE TITLE
JSONB serialization

### ISSUE THREAD

**Issue by kmcintyre** [marshmallow-code/marshmallow-sqlalchemy#87]
I'm using posgres 

<pre>
class Entity(Base):
    id = Column(Integer, primary_key=True)
    properties = Column(JSONB)
</pre>

but when I serialize to json I do not see the properties key.

**Comment by sloria** [comment]
Which version of marshmallow-sqlalchemy are you using?

**Comment by kmcintyre** [comment]
## pip show marshmallow-sqlalchemy

Metadata-Version: 2.0
Name: marshmallow-sqlalchemy
Version: 0.10.0
Summary: SQLAlchemy integration with the marshmallow (de)serialization library
Home-page: https://github.com/marshmallow-code/marshmallow-sqlalchemy
Author: Steven Loria
Author-email: ---
Installer: pip
License: Copyright 2015-2016 Steven Loria, Joshua Carp, and contributors
Location: /usr/local/lib/python2.7/dist-packages
Requires: marshmallow, SQLAlchemy
Classifiers:

**Comment by kmcintyre** [comment]
Do'h -- totally works -- I'm an idiot.
