### ISSUE TITLE
Deserialization with relationships always triggers SqlAlchemy history change

### ISSUE THREAD

**Issue by nochristrequired** [marshmallow-code/marshmallow-sqlalchemy#96]
Hi,

I have tables with relationships. The issue I'm seeing is that the child relationships seem to not be evaluated based on their values before a new instance of that relationship is merged on top. I can see in the SQLAlchemy history API that the object references change, but no values have changed - this causes SQLAlchemy to generate unnecessary update statements.

I am wondering if someone can advise on how to use Marshmallow to check the values first and not create a replacement SQLAlchemy child object. Is it possible to somehow leverage pre_load to check and throw out the values or prevent mm-sqlalchemy from creating the object that way?

Thanks in advance!

**Comment by nochristrequired** [comment]
This is an example of the attribute state from the SQLAlchemy History API after deserialization on top of an existing row using marshmallow-sqlalchemy. The object being deserialized was exactly the same as in the database. We can see in the output below that we have two account_alias objects associated with this account (two rows in the table.) 

No values change - seems that mm-sqlalchemy removed the objects pulled from the database, then added the values from the deserialization operation even though they all had the same values and matched exactly (except the pointer.)

`History(added=[<datarepo.types.sa_models.sa__account.account_alias object at 0xfb0af710>, <datarepo.types.sa_models.sa_account.account_alias object at 0xfb0af770>], unchanged=[], deleted=[<datarepo.types.sa_models.sa_account.account_alias object at 0xfb0da1f0>, <datarepo.types.sa_models.sa_account.account_alias object at 0xfb0da270>])`

Any help would be greatly appreciated. I understand if I need to do the evaluation of the object myself to determine if it is unique - my question is, how to approach this?

**Comment by nochristrequired** [comment]
Update - I implemented **eq** on my relationship, what I see is a mismatch with the comparison. For example, an account has two alias entries, the **eq** is called, but in the wrong order, so that row 1 is compared with row 2, and then row 2 with row 1... I think **eq** would probably otherwise work for this issue.

**Comment by sloria** [comment]
ma-sqla now supports [transient object creation](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#transient-object-creation), which may solve this issue.

Closing for now since this is stale. Feel free to comment if this is still an issue
